//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Parsers.Gs1Ai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gs1ApplicationIdentifier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gs1ApplicationIdentifier() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Parsers.Gs1Ai.Properties.Gs1ApplicationIdentifier", typeof(Gs1ApplicationIdentifier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of a logistic unit (SSCC).
        /// </summary>
        internal static string ai00 {
            get {
                return ResourceManager.GetString("ai00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of a trade item (GTIN).
        /// </summary>
        internal static string ai01 {
            get {
                return ResourceManager.GetString("ai01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of trade items contained in a logistic unit.
        /// </summary>
        internal static string ai02 {
            get {
                return ResourceManager.GetString("ai02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch or lot number.
        /// </summary>
        internal static string ai10 {
            get {
                return ResourceManager.GetString("ai10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date.
        /// </summary>
        internal static string ai11 {
            get {
                return ResourceManager.GetString("ai11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date for amount on payment slip.
        /// </summary>
        internal static string ai12 {
            get {
                return ResourceManager.GetString("ai12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging date.
        /// </summary>
        internal static string ai13 {
            get {
                return ResourceManager.GetString("ai13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best before date.
        /// </summary>
        internal static string ai15 {
            get {
                return ResourceManager.GetString("ai15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell by date.
        /// </summary>
        internal static string ai16 {
            get {
                return ResourceManager.GetString("ai16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string ai17 {
            get {
                return ResourceManager.GetString("ai17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal product variant.
        /// </summary>
        internal static string ai20 {
            get {
                return ResourceManager.GetString("ai20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string ai21 {
            get {
                return ResourceManager.GetString("ai21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer product variant.
        /// </summary>
        internal static string ai22 {
            get {
                return ResourceManager.GetString("ai22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Controlled, Serialised Extension of Global Trade Item Number (GTIN) (TPX).
        /// </summary>
        internal static string ai235 {
            get {
                return ResourceManager.GetString("ai235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional product identification assigned by the manufacturer.
        /// </summary>
        internal static string ai240 {
            get {
                return ResourceManager.GetString("ai240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer part number.
        /// </summary>
        internal static string ai241 {
            get {
                return ResourceManager.GetString("ai241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made-to-Order variation number.
        /// </summary>
        internal static string ai242 {
            get {
                return ResourceManager.GetString("ai242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging component number.
        /// </summary>
        internal static string ai243 {
            get {
                return ResourceManager.GetString("ai243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary serial number.
        /// </summary>
        internal static string ai250 {
            get {
                return ResourceManager.GetString("ai250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to source entity.
        /// </summary>
        internal static string ai251 {
            get {
                return ResourceManager.GetString("ai251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Document Type Identifier (GDTI).
        /// </summary>
        internal static string ai253 {
            get {
                return ResourceManager.GetString("ai253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Location Number (GLN) extension component.
        /// </summary>
        internal static string ai254 {
            get {
                return ResourceManager.GetString("ai254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Coupon Number (GCN).
        /// </summary>
        internal static string ai255 {
            get {
                return ResourceManager.GetString("ai255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable count of items.
        /// </summary>
        internal static string ai30 {
            get {
                return ResourceManager.GetString("ai30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight, kilograms (variable measure trade item).
        /// </summary>
        internal static string ai310n {
            get {
                return ResourceManager.GetString("ai310n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, metres (variable measure trade item).
        /// </summary>
        internal static string ai311n {
            get {
                return ResourceManager.GetString("ai311n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, metres (variable measure trade item).
        /// </summary>
        internal static string ai312n {
            get {
                return ResourceManager.GetString("ai312n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, metres (variable measure trade item).
        /// </summary>
        internal static string ai313n {
            get {
                return ResourceManager.GetString("ai313n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square metres (variable measure trade item).
        /// </summary>
        internal static string ai314n {
            get {
                return ResourceManager.GetString("ai314n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, litres (variable measure trade item).
        /// </summary>
        internal static string ai315n {
            get {
                return ResourceManager.GetString("ai315n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, cubic metres (variable measure trade item).
        /// </summary>
        internal static string ai316n {
            get {
                return ResourceManager.GetString("ai316n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight, pounds (variable measure trade item).
        /// </summary>
        internal static string ai320n {
            get {
                return ResourceManager.GetString("ai320n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, inches (variable measure trade item).
        /// </summary>
        internal static string ai321n {
            get {
                return ResourceManager.GetString("ai321n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, feet (variable measure trade item).
        /// </summary>
        internal static string ai322n {
            get {
                return ResourceManager.GetString("ai322n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, yards (variable measure trade item).
        /// </summary>
        internal static string ai323n {
            get {
                return ResourceManager.GetString("ai323n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, inches (variable measure trade item).
        /// </summary>
        internal static string ai324n {
            get {
                return ResourceManager.GetString("ai324n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, feet (variable measure trade item).
        /// </summary>
        internal static string ai325n {
            get {
                return ResourceManager.GetString("ai325n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, yards (variable measure trade item).
        /// </summary>
        internal static string ai326n {
            get {
                return ResourceManager.GetString("ai326n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, inches (variable measure trade item).
        /// </summary>
        internal static string ai327n {
            get {
                return ResourceManager.GetString("ai327n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, feet (variable measure trade item).
        /// </summary>
        internal static string ai328n {
            get {
                return ResourceManager.GetString("ai328n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, yards (variable measure trade item).
        /// </summary>
        internal static string ai329n {
            get {
                return ResourceManager.GetString("ai329n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic weight, kilograms.
        /// </summary>
        internal static string ai330n {
            get {
                return ResourceManager.GetString("ai330n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, metres.
        /// </summary>
        internal static string ai331n {
            get {
                return ResourceManager.GetString("ai331n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, metres.
        /// </summary>
        internal static string ai332n {
            get {
                return ResourceManager.GetString("ai332n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, metres.
        /// </summary>
        internal static string ai333n {
            get {
                return ResourceManager.GetString("ai333n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square metres.
        /// </summary>
        internal static string ai334n {
            get {
                return ResourceManager.GetString("ai334n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, litres.
        /// </summary>
        internal static string ai335n {
            get {
                return ResourceManager.GetString("ai335n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, cubic metres.
        /// </summary>
        internal static string ai336n {
            get {
                return ResourceManager.GetString("ai336n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms per square metre.
        /// </summary>
        internal static string ai337n {
            get {
                return ResourceManager.GetString("ai337n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic weight, pounds.
        /// </summary>
        internal static string ai340n {
            get {
                return ResourceManager.GetString("ai340n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, inches.
        /// </summary>
        internal static string ai341n {
            get {
                return ResourceManager.GetString("ai341n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, feet.
        /// </summary>
        internal static string ai342n {
            get {
                return ResourceManager.GetString("ai342n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length or first dimension, yards.
        /// </summary>
        internal static string ai343n {
            get {
                return ResourceManager.GetString("ai343n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, inches.
        /// </summary>
        internal static string ai344n {
            get {
                return ResourceManager.GetString("ai344n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, feet.
        /// </summary>
        internal static string ai345n {
            get {
                return ResourceManager.GetString("ai345n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, diameter, or second dimension, yard.
        /// </summary>
        internal static string ai346n {
            get {
                return ResourceManager.GetString("ai346n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, inches.
        /// </summary>
        internal static string ai347n {
            get {
                return ResourceManager.GetString("ai347n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, feet.
        /// </summary>
        internal static string ai348n {
            get {
                return ResourceManager.GetString("ai348n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth, thickness, height, or third dimension, yards.
        /// </summary>
        internal static string ai349n {
            get {
                return ResourceManager.GetString("ai349n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square inches (variable measure trade item).
        /// </summary>
        internal static string ai350n {
            get {
                return ResourceManager.GetString("ai350n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square feet (variable measure trade item).
        /// </summary>
        internal static string ai351n {
            get {
                return ResourceManager.GetString("ai351n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square yards (variable measure trade item).
        /// </summary>
        internal static string ai352n {
            get {
                return ResourceManager.GetString("ai352n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square inches.
        /// </summary>
        internal static string ai353n {
            get {
                return ResourceManager.GetString("ai353n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square feet.
        /// </summary>
        internal static string ai354n {
            get {
                return ResourceManager.GetString("ai354n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area, square yards.
        /// </summary>
        internal static string ai355n {
            get {
                return ResourceManager.GetString("ai355n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight, troy ounces (variable measure trade item).
        /// </summary>
        internal static string ai356n {
            get {
                return ResourceManager.GetString("ai356n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight (or volume), ounces (variable measure trade item).
        /// </summary>
        internal static string ai357n {
            get {
                return ResourceManager.GetString("ai357n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, quarts (variable measure trade item).
        /// </summary>
        internal static string ai360n {
            get {
                return ResourceManager.GetString("ai360n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, gallons U.S. (variable measure trade item).
        /// </summary>
        internal static string ai361n {
            get {
                return ResourceManager.GetString("ai361n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, quarts.
        /// </summary>
        internal static string ai362n {
            get {
                return ResourceManager.GetString("ai362n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, gallons U.S..
        /// </summary>
        internal static string ai363n {
            get {
                return ResourceManager.GetString("ai363n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, cubic inches (variable measure trade item).
        /// </summary>
        internal static string ai364n {
            get {
                return ResourceManager.GetString("ai364n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, cubic feet (variable measure trade item).
        /// </summary>
        internal static string ai365n {
            get {
                return ResourceManager.GetString("ai365n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net volume, cubic yards (variable measure trade item).
        /// </summary>
        internal static string ai366n {
            get {
                return ResourceManager.GetString("ai366n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, cubic inches.
        /// </summary>
        internal static string ai367n {
            get {
                return ResourceManager.GetString("ai367n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, cubic feet.
        /// </summary>
        internal static string ai368n {
            get {
                return ResourceManager.GetString("ai368n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic volume, cubic yards.
        /// </summary>
        internal static string ai369n {
            get {
                return ResourceManager.GetString("ai369n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of trade items or trade item pieces contained in a logistic unit.
        /// </summary>
        internal static string ai37 {
            get {
                return ResourceManager.GetString("ai37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount payable or coupon value - Single monetary area.
        /// </summary>
        internal static string ai390n {
            get {
                return ResourceManager.GetString("ai390n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount payable and ISO currency code.
        /// </summary>
        internal static string ai391n {
            get {
                return ResourceManager.GetString("ai391n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount payable for a variable measure trade item - Single monetary area.
        /// </summary>
        internal static string ai392n {
            get {
                return ResourceManager.GetString("ai392n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount payable for a variable measure trade item and ISO currency code.
        /// </summary>
        internal static string ai393n {
            get {
                return ResourceManager.GetString("ai393n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage discount of a coupon.
        /// </summary>
        internal static string ai394n {
            get {
                return ResourceManager.GetString("ai394n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount payable per unit of measure single monetary area (variable measure trade item).
        /// </summary>
        internal static string ai395n {
            get {
                return ResourceManager.GetString("ai395n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s purchase order number.
        /// </summary>
        internal static string ai400 {
            get {
                return ResourceManager.GetString("ai400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Identification Number for Consignment (GINC).
        /// </summary>
        internal static string ai401 {
            get {
                return ResourceManager.GetString("ai401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Shipment Identification Number (GSIN).
        /// </summary>
        internal static string ai402 {
            get {
                return ResourceManager.GetString("ai402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing code.
        /// </summary>
        internal static string ai403 {
            get {
                return ResourceManager.GetString("ai403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship to - Deliver to Global Location Number (GLN).
        /// </summary>
        internal static string ai410 {
            get {
                return ResourceManager.GetString("ai410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill to - Invoice to Global Location Number (GLN).
        /// </summary>
        internal static string ai411 {
            get {
                return ResourceManager.GetString("ai411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased from Global Location Number (GLN).
        /// </summary>
        internal static string ai412 {
            get {
                return ResourceManager.GetString("ai412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship for - Deliver for - Forward to Global Location Number (GLN).
        /// </summary>
        internal static string ai413 {
            get {
                return ResourceManager.GetString("ai413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of a physical location - Global Location Number (GLN).
        /// </summary>
        internal static string ai414 {
            get {
                return ResourceManager.GetString("ai414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Location Number (GLN) of the invoicing party.
        /// </summary>
        internal static string ai415 {
            get {
                return ResourceManager.GetString("ai415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Location Number (GLN) of the production or service location.
        /// </summary>
        internal static string ai416 {
            get {
                return ResourceManager.GetString("ai416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Global Location Number (GLN).
        /// </summary>
        internal static string ai417 {
            get {
                return ResourceManager.GetString("ai417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to postal code within a single postal authority.
        /// </summary>
        internal static string ai420 {
            get {
                return ResourceManager.GetString("ai420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to postal code with three-digit ISO country code.
        /// </summary>
        internal static string ai421 {
            get {
                return ResourceManager.GetString("ai421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin of a trade item.
        /// </summary>
        internal static string ai422 {
            get {
                return ResourceManager.GetString("ai422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of initial processing.
        /// </summary>
        internal static string ai423 {
            get {
                return ResourceManager.GetString("ai423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of processing.
        /// </summary>
        internal static string ai424 {
            get {
                return ResourceManager.GetString("ai424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of disassembly.
        /// </summary>
        internal static string ai425 {
            get {
                return ResourceManager.GetString("ai425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country covering full process chain.
        /// </summary>
        internal static string ai426 {
            get {
                return ResourceManager.GetString("ai426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country subdivision of origin code for a trade item.
        /// </summary>
        internal static string ai427 {
            get {
                return ResourceManager.GetString("ai427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to Company name.
        /// </summary>
        internal static string ai4300 {
            get {
                return ResourceManager.GetString("ai4300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to contact name.
        /// </summary>
        internal static string ai4301 {
            get {
                return ResourceManager.GetString("ai4301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to address line 1.
        /// </summary>
        internal static string ai4302 {
            get {
                return ResourceManager.GetString("ai4302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to address line 2.
        /// </summary>
        internal static string ai4303 {
            get {
                return ResourceManager.GetString("ai4303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to suburb.
        /// </summary>
        internal static string ai4304 {
            get {
                return ResourceManager.GetString("ai4304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to locality.
        /// </summary>
        internal static string ai4305 {
            get {
                return ResourceManager.GetString("ai4305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to region.
        /// </summary>
        internal static string ai4306 {
            get {
                return ResourceManager.GetString("ai4306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to country code.
        /// </summary>
        internal static string ai4307 {
            get {
                return ResourceManager.GetString("ai4307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to telephone number.
        /// </summary>
        internal static string ai4308 {
            get {
                return ResourceManager.GetString("ai4308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-to / Deliver-to GEO location.
        /// </summary>
        internal static string ai4309 {
            get {
                return ResourceManager.GetString("ai4309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to company name.
        /// </summary>
        internal static string ai4310 {
            get {
                return ResourceManager.GetString("ai4310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to contact name.
        /// </summary>
        internal static string ai4311 {
            get {
                return ResourceManager.GetString("ai4311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to address line 1.
        /// </summary>
        internal static string ai4312 {
            get {
                return ResourceManager.GetString("ai4312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to address line 2.
        /// </summary>
        internal static string ai4313 {
            get {
                return ResourceManager.GetString("ai4313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to suburb.
        /// </summary>
        internal static string ai4314 {
            get {
                return ResourceManager.GetString("ai4314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to locality.
        /// </summary>
        internal static string ai4315 {
            get {
                return ResourceManager.GetString("ai4315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to region.
        /// </summary>
        internal static string ai4316 {
            get {
                return ResourceManager.GetString("ai4316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to country code.
        /// </summary>
        internal static string ai4317 {
            get {
                return ResourceManager.GetString("ai4317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to postal code.
        /// </summary>
        internal static string ai4318 {
            get {
                return ResourceManager.GetString("ai4318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-to telephone number.
        /// </summary>
        internal static string ai4319 {
            get {
                return ResourceManager.GetString("ai4319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service code description.
        /// </summary>
        internal static string ai4320 {
            get {
                return ResourceManager.GetString("ai4320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous goods flag.
        /// </summary>
        internal static string ai4321 {
            get {
                return ResourceManager.GetString("ai4321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority to leave flag.
        /// </summary>
        internal static string ai4322 {
            get {
                return ResourceManager.GetString("ai4322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature required flag.
        /// </summary>
        internal static string ai4323 {
            get {
                return ResourceManager.GetString("ai4323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not before delivery date/time.
        /// </summary>
        internal static string ai4324 {
            get {
                return ResourceManager.GetString("ai4324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not after delivery date/time.
        /// </summary>
        internal static string ai4325 {
            get {
                return ResourceManager.GetString("ai4325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        internal static string ai4326 {
            get {
                return ResourceManager.GetString("ai4326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum temperature in Fahrenheit.
        /// </summary>
        internal static string ai4330 {
            get {
                return ResourceManager.GetString("ai4330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum temperature in Celsius.
        /// </summary>
        internal static string ai4331 {
            get {
                return ResourceManager.GetString("ai4331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature in Fahrenheit.
        /// </summary>
        internal static string ai4332 {
            get {
                return ResourceManager.GetString("ai4332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature in Celsius.
        /// </summary>
        internal static string ai4333 {
            get {
                return ResourceManager.GetString("ai4333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATO Stock Number (NSN).
        /// </summary>
        internal static string ai7001 {
            get {
                return ResourceManager.GetString("ai7001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNECE meat carcasses and cuts classification.
        /// </summary>
        internal static string ai7002 {
            get {
                return ResourceManager.GetString("ai7002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date and time.
        /// </summary>
        internal static string ai7003 {
            get {
                return ResourceManager.GetString("ai7003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active potency.
        /// </summary>
        internal static string ai7004 {
            get {
                return ResourceManager.GetString("ai7004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch area.
        /// </summary>
        internal static string ai7005 {
            get {
                return ResourceManager.GetString("ai7005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First freeze date.
        /// </summary>
        internal static string ai7006 {
            get {
                return ResourceManager.GetString("ai7006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest date.
        /// </summary>
        internal static string ai7007 {
            get {
                return ResourceManager.GetString("ai7007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species for fishery purposes.
        /// </summary>
        internal static string ai7008 {
            get {
                return ResourceManager.GetString("ai7008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing gear type.
        /// </summary>
        internal static string ai7009 {
            get {
                return ResourceManager.GetString("ai7009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production method.
        /// </summary>
        internal static string ai7010 {
            get {
                return ResourceManager.GetString("ai7010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test by date.
        /// </summary>
        internal static string ai7011 {
            get {
                return ResourceManager.GetString("ai7011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refurbishment lot ID.
        /// </summary>
        internal static string ai7020 {
            get {
                return ResourceManager.GetString("ai7020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional status.
        /// </summary>
        internal static string ai7021 {
            get {
                return ResourceManager.GetString("ai7021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision status.
        /// </summary>
        internal static string ai7022 {
            get {
                return ResourceManager.GetString("ai7022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Individual Asset Identifier of an assembly.
        /// </summary>
        internal static string ai7023 {
            get {
                return ResourceManager.GetString("ai7023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of processor with three-digit ISO country code.
        /// </summary>
        internal static string ai703s {
            get {
                return ResourceManager.GetString("ai703s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS1 UIC with Extension 1 and Importer index.
        /// </summary>
        internal static string ai7040 {
            get {
                return ResourceManager.GetString("ai7040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Healthcare Reimbursement Number (NHRN) - Germany PZN.
        /// </summary>
        internal static string ai710 {
            get {
                return ResourceManager.GetString("ai710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Healthcare Reimbursement Number (NHRN) - France CIP.
        /// </summary>
        internal static string ai711 {
            get {
                return ResourceManager.GetString("ai711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Healthcare Reimbursement Number (NHRN) - Spain CN.
        /// </summary>
        internal static string ai712 {
            get {
                return ResourceManager.GetString("ai712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Healthcare Reimbursement Number (NHRN) - Brasil DRN.
        /// </summary>
        internal static string ai713 {
            get {
                return ResourceManager.GetString("ai713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Healthcare Reimbursement Number (NHRN) - Portugal AIM.
        /// </summary>
        internal static string ai714 {
            get {
                return ResourceManager.GetString("ai714", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Healthcare Reimbursement Number (NHRN) - United States of America NDC.
        /// </summary>
        internal static string ai715 {
            get {
                return ResourceManager.GetString("ai715", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification reference.
        /// </summary>
        internal static string ai723s {
            get {
                return ResourceManager.GetString("ai723s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol ID.
        /// </summary>
        internal static string ai7240 {
            get {
                return ResourceManager.GetString("ai7240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIDC media type.
        /// </summary>
        internal static string ai7241 {
            get {
                return ResourceManager.GetString("ai7241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Control Number (VCN).
        /// </summary>
        internal static string ai7242 {
            get {
                return ResourceManager.GetString("ai7242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll products - width, length, core diameter, direction, splices.
        /// </summary>
        internal static string ai8001 {
            get {
                return ResourceManager.GetString("ai8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular mobile telephone identifier.
        /// </summary>
        internal static string ai8002 {
            get {
                return ResourceManager.GetString("ai8002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Returnable Asset Identifier (GRAI).
        /// </summary>
        internal static string ai8003 {
            get {
                return ResourceManager.GetString("ai8003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Individual Asset Identifier (GIAI).
        /// </summary>
        internal static string ai8004 {
            get {
                return ResourceManager.GetString("ai8004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per unit of measure.
        /// </summary>
        internal static string ai8005 {
            get {
                return ResourceManager.GetString("ai8005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of an individual trade item (ITIP) piece.
        /// </summary>
        internal static string ai8006 {
            get {
                return ResourceManager.GetString("ai8006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Bank Account Number (IBAN).
        /// </summary>
        internal static string ai8007 {
            get {
                return ResourceManager.GetString("ai8007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time of production.
        /// </summary>
        internal static string ai8008 {
            get {
                return ResourceManager.GetString("ai8008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optically readable sensor indicator.
        /// </summary>
        internal static string ai8009 {
            get {
                return ResourceManager.GetString("ai8009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component/Part Identifier (CPID).
        /// </summary>
        internal static string ai8010 {
            get {
                return ResourceManager.GetString("ai8010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component/Part Identifier serial number.
        /// </summary>
        internal static string ai8011 {
            get {
                return ResourceManager.GetString("ai8011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version.
        /// </summary>
        internal static string ai8012 {
            get {
                return ResourceManager.GetString("ai8012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Model Number (GMN).
        /// </summary>
        internal static string ai8013 {
            get {
                return ResourceManager.GetString("ai8013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Service Relation Number (GSRN) to identify the relationship between an organisation offering services and the provider of services.
        /// </summary>
        internal static string ai8017 {
            get {
                return ResourceManager.GetString("ai8017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Service Relation Number (GSRN) to identify the relationship between an organisation offering services and the recipient of services.
        /// </summary>
        internal static string ai8018 {
            get {
                return ResourceManager.GetString("ai8018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Relation Instance Number (SRIN).
        /// </summary>
        internal static string ai8019 {
            get {
                return ResourceManager.GetString("ai8019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment slip reference number.
        /// </summary>
        internal static string ai8020 {
            get {
                return ResourceManager.GetString("ai8020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of pieces of a trade item (ITIP) contained in a logistic unit.
        /// </summary>
        internal static string ai8026 {
            get {
                return ResourceManager.GetString("ai8026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature (DigSig).
        /// </summary>
        internal static string ai8030 {
            get {
                return ResourceManager.GetString("ai8030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon code identification for use in North America.
        /// </summary>
        internal static string ai8110 {
            get {
                return ResourceManager.GetString("ai8110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points of a coupon.
        /// </summary>
        internal static string ai8111 {
            get {
                return ResourceManager.GetString("ai8111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive offer file coupon code identification for use in North America.
        /// </summary>
        internal static string ai8112 {
            get {
                return ResourceManager.GetString("ai8112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended packaging URL.
        /// </summary>
        internal static string ai8200 {
            get {
                return ResourceManager.GetString("ai8200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information mutually agreed between trading partners.
        /// </summary>
        internal static string ai90 {
            get {
                return ResourceManager.GetString("ai90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai91 {
            get {
                return ResourceManager.GetString("ai91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai92 {
            get {
                return ResourceManager.GetString("ai92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai93 {
            get {
                return ResourceManager.GetString("ai93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai94 {
            get {
                return ResourceManager.GetString("ai94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai95 {
            get {
                return ResourceManager.GetString("ai95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai96 {
            get {
                return ResourceManager.GetString("ai96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai97 {
            get {
                return ResourceManager.GetString("ai97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai98 {
            get {
                return ResourceManager.GetString("ai98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company internal information.
        /// </summary>
        internal static string ai99 {
            get {
                return ResourceManager.GetString("ai99", resourceCulture);
            }
        }
    }
}
