//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Parsers.Gs1Ai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gs1CountryCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gs1CountryCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Parsers.Gs1Ai.Properties.Gs1CountryCode", typeof(Gs1CountryCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string Albania {
            get {
                return ResourceManager.GetString("Albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        internal static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        internal static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        internal static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        internal static string Bangladesh {
            get {
                return ResourceManager.GetString("Bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium And Luxembourg.
        /// </summary>
        internal static string BelgiumAndLuxembourg {
            get {
                return ResourceManager.GetString("BelgiumAndLuxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        internal static string Bolivia {
            get {
                return ResourceManager.GetString("Bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookland (ISBN).
        /// </summary>
        internal static string BooklandIsbn {
            get {
                return ResourceManager.GetString("BooklandIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookland (ISBN) - sheet music (ISMN-13).
        /// </summary>
        internal static string BooklandIsbnIsmn {
            get {
                return ResourceManager.GetString("BooklandIsbnIsmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        internal static string BosniaAndHerzegovina {
            get {
                return ResourceManager.GetString("BosniaAndHerzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei.
        /// </summary>
        internal static string Brunei {
            get {
                return ResourceManager.GetString("Brunei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        internal static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string CostaRica {
            get {
                return ResourceManager.GetString("CostaRica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon identification.
        /// </summary>
        internal static string CouponIdentification {
            get {
                return ResourceManager.GetString("CouponIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS1 coupon identification for common currency areas.
        /// </summary>
        internal static string CouponIdentificationForCommonCurrencyArea {
            get {
                return ResourceManager.GetString("CouponIdentificationForCommonCurrencyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        internal static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        internal static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        internal static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        internal static string CzechRepublic {
            get {
                return ResourceManager.GetString("CzechRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark, Faroe Islands and Greenland.
        /// </summary>
        internal static string DenmarkFaroeIslandsAndGreenland {
            get {
                return ResourceManager.GetString("DenmarkFaroeIslandsAndGreenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        internal static string DominicanRepublic {
            get {
                return ResourceManager.GetString("DominicanRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        internal static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        internal static string ElSalvador {
            get {
                return ResourceManager.GetString("ElSalvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        internal static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland     .
        /// </summary>
        internal static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France and Monaco.
        /// </summary>
        internal static string FranceAndMonaco {
            get {
                return ResourceManager.GetString("FranceAndMonaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Manager Numbers for the EPC General Identifier (GID) scheme as defined by the EPC Tag Data Standard.
        /// </summary>
        internal static string GeneralManagerNumber {
            get {
                return ResourceManager.GetString("GeneralManagerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string Georgia {
            get {
                return ResourceManager.GetString("Georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        internal static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Office - special application.
        /// </summary>
        internal static string GlobalOffice {
            get {
                return ResourceManager.GetString("GlobalOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS1 Global Office: GTIN-8 allocation.
        /// </summary>
        internal static string GlobalOfficeGtin8Allocation {
            get {
                return ResourceManager.GetString("GlobalOfficeGtin8Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        internal static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        internal static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        internal static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary     .
        /// </summary>
        internal static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        internal static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        internal static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        internal static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy, San Marino and Vatican City.
        /// </summary>
        internal static string ItalySanMarinoAndVaticanCity {
            get {
                return ResourceManager.GetString("ItalySanMarinoAndVaticanCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory Coast.
        /// </summary>
        internal static string IvoryCoast {
            get {
                return ResourceManager.GetString("IvoryCoast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan (new Japanese Article Number range).
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan (original Japanese Article Number range).
        /// </summary>
        internal static string JapanOriginalJan {
            get {
                return ResourceManager.GetString("JapanOriginalJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        internal static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        internal static string Kazakhstan {
            get {
                return ResourceManager.GetString("Kazakhstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        internal static string Kenya {
            get {
                return ResourceManager.GetString("Kenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosovo.
        /// </summary>
        internal static string Kosovo {
            get {
                return ResourceManager.GetString("Kosovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstan.
        /// </summary>
        internal static string Kyrgyzstan {
            get {
                return ResourceManager.GetString("Kyrgyzstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        internal static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        internal static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        internal static string Libya {
            get {
                return ResourceManager.GetString("Libya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        internal static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macau.
        /// </summary>
        internal static string Macau {
            get {
                return ResourceManager.GetString("Macau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        internal static string Malaysia {
            get {
                return ResourceManager.GetString("Malaysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        internal static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        internal static string Mauritius {
            get {
                return ResourceManager.GetString("Mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova.
        /// </summary>
        internal static string Moldova {
            get {
                return ResourceManager.GetString("Moldova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        internal static string Mongolia {
            get {
                return ResourceManager.GetString("Mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        internal static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string NewZealand {
            get {
                return ResourceManager.GetString("NewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string Nicaragua {
            get {
                return ResourceManager.GetString("Nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        internal static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Korea.
        /// </summary>
        internal static string NorthKorea {
            get {
                return ResourceManager.GetString("NorthKorea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia.
        /// </summary>
        internal static string NorthMacedonia {
            get {
                return ResourceManager.GetString("NorthMacedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        internal static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string Panama {
            get {
                return ResourceManager.GetString("Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        internal static string Paraguay {
            get {
                return ResourceManager.GetString("Paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peoples Republic of China.
        /// </summary>
        internal static string PeoplesRepublicOfChina {
            get {
                return ResourceManager.GetString("PeoplesRepublicOfChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        internal static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Receipt.
        /// </summary>
        internal static string RefundReceipt {
            get {
                return ResourceManager.GetString("RefundReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to issue a GS1 restricted circulation number within a geographic region.
        /// </summary>
        internal static string RestrictedCirculation {
            get {
                return ResourceManager.GetString("RestrictedCirculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        internal static string SaudiArabia {
            get {
                return ResourceManager.GetString("SaudiArabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        internal static string Senegal {
            get {
                return ResourceManager.GetString("Senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial publications (ISSN).
        /// </summary>
        internal static string SerialPublicationIssn {
            get {
                return ResourceManager.GetString("SerialPublicationIssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        internal static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        internal static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        internal static string SouthAfrica {
            get {
                return ResourceManager.GetString("SouthAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea.
        /// </summary>
        internal static string SouthKorea {
            get {
                return ResourceManager.GetString("SouthKorea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain and Andorra.
        /// </summary>
        internal static string SpainAndAndorra {
            get {
                return ResourceManager.GetString("SpainAndAndorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        internal static string SriLanka {
            get {
                return ResourceManager.GetString("SriLanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland and Liechtenstein.
        /// </summary>
        internal static string SwitzerlandAndLiechtenstein {
            get {
                return ResourceManager.GetString("SwitzerlandAndLiechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        internal static string Syria {
            get {
                return ResourceManager.GetString("Syria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Republic of China (Taiwan).
        /// </summary>
        internal static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        internal static string Tajikistan {
            get {
                return ResourceManager.GetString("Tajikistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania.
        /// </summary>
        internal static string Tanzania {
            get {
                return ResourceManager.GetString("Tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        internal static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        internal static string Tunisia {
            get {
                return ResourceManager.GetString("Tunisia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        internal static string Turkmenistan {
            get {
                return ResourceManager.GetString("Turkmenistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        internal static string UnitedArabEmirates {
            get {
                return ResourceManager.GetString("UnitedArabEmirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string UnitedKingdom {
            get {
                return ResourceManager.GetString("UnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS1 UK Office: GTIN-8 allocation.
        /// </summary>
        internal static string UnitedKingdomOfficeGtin8Allocation {
            get {
                return ResourceManager.GetString("UnitedKingdomOfficeGtin8Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved by GS1 Global Office for allocations in non-member countries and for future use.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC-A compatible (GTIN 8).
        /// </summary>
        internal static string UpcACompatibleGtin8 {
            get {
                return ResourceManager.GetString("UpcACompatibleGtin8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC-A compatible - Used to issue restricted circulation numbers within a geographic region.
        /// </summary>
        internal static string UpcACompatibleRestrictedCirculation {
            get {
                return ResourceManager.GetString("UpcACompatibleRestrictedCirculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC-A compatible - United States and Canada.
        /// </summary>
        internal static string UpcACompatibleUnitedStatesAndCanada {
            get {
                return ResourceManager.GetString("UpcACompatibleUnitedStatesAndCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC-A compatible -  United States drugs (National Drug Code).
        /// </summary>
        internal static string UpcACompatibleUnitedStatesDrugs {
            get {
                return ResourceManager.GetString("UpcACompatibleUnitedStatesDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC-A compatible - United States reserved for future use.
        /// </summary>
        internal static string UpcACompatibleUnitedStatesReserved {
            get {
                return ResourceManager.GetString("UpcACompatibleUnitedStatesReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay     .
        /// </summary>
        internal static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string Uzbekistan {
            get {
                return ResourceManager.GetString("Uzbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        internal static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        internal static string Vietnam {
            get {
                return ResourceManager.GetString("Vietnam", resourceCulture);
            }
        }
    }
}
