// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Solidsoft.Reply.Parsers.Gs1Ai.Tests.Net5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ElementStringsFeature : object, global::Xunit.IClassFixture<ElementStringsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "ElementStrings", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ElementStrings.feature"
#line hidden
        
        public ElementStringsFeature(ElementStringsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ElementStrings.feature.ndjson", 215);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Parentheses in Fixed Length Element Strings")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ElementStrings")]
        [global::Xunit.TraitAttribute("Description", "Parentheses in Fixed Length Element Strings")]
        [global::Xunit.InlineDataAttribute("(00)001234560000000018", "00", "00", "001234560000000018", "SSCC", "Identification of a logistic unit (SSCC)", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("(01)12345678901231", "01", "01", "12345678901231", "GTIN", "Identification of a trade item (GTIN)", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("(02)12345678901231", "02", "02", "12345678901231", "CONTENT", "Identification of trade items contained in a logistic unit", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("(03)12345678901231", "03", "03", "12345678901231", "MTO GTIN", "Identification of a Made-to-Order (MtO) trade item (GTIN)", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("(11)231231", "11", "11", "231231", "PROD DATE", "Production date", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("(12)231231", "12", "12", "231231", "DUE DATE", "Due date for amount on payment slip", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("(13)231231", "13", "13", "231231", "PACK DATE", "Packaging date", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("(15)231231", "15", "15", "231231", "BEST BEFORE or BEST BY", "Best before date", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("(16)231231", "16", "16", "231231", "SELL BY", "Sell by date", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("(17)231231", "17", "17", "231231", "USE BY OR EXPIRY", "Expiration date", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("(20)01", "20", "20", "01", "VARIANT", "Internal product variant", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("(402)50609175112345629", "402", "402", "50609175112345629", "GSIN", "Global Shipment Identification Number (GSIN)", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("(410)5060917510004", "410", "410", "5060917510004", "SHIP TO LOC", "Ship to - Deliver to Global Location Number (GLN)", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("(411)5060917510004", "411", "411", "5060917510004", "BILL TO", "Bill to - Invoice to Global Location Number (GLN)", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("(412)5060917510004", "412", "412", "5060917510004", "PURCHASE FROM", "Purchased from Global Location Number (GLN)", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("(413)5060917510004", "413", "413", "5060917510004", "SHIP FOR LOC", "Ship for - Deliver for - Forward to Global Location Number (GLN)", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("(414)5060917510004", "414", "414", "5060917510004", "LOC No.", "Identification of a physical location - Global Location Number (GLN)", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("(415)5060917510004", "415", "415", "5060917510004", "PAY TO", "Global Location Number (GLN) of the invoicing party", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("(416)5060917510004", "416", "416", "5060917510004", "PROD/SERV LOC", "Global Location Number (GLN) of the production or service location", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("(417)5060917510004", "417", "417", "5060917510004", "PARTY", "Party Global Location Number (GLN)", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("(422)826", "422", "422", "826", "ORIGIN", "Country of origin of a trade item", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("(424)826", "424", "424", "826", "COUNTRY - PROCESS", "Country of processing", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("(426)826", "426", "426", "826", "COUNTRY – FULL PROCESS", "Country covering full process chain", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("(4307)GB", "4307", "4307", "GB", "SHIP TO COUNTRY", "Ship-to / Deliver-to country code", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("(4309)02790858483015297971", "4309", "4309", "02790858483015297971", "SHIP TO GEO", "Ship-to / Deliver-to GEO location", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("(4317)GB", "4317", "4317", "GB", "RTN TO COUNTRY", "Return-to country code", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("(4321)1", "4321", "4321", "1", "DANGEROUS GOODS", "Dangerous goods flag", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("(4322)1", "4322", "4322", "1", "AUTH LEAVE", "Authority to leave flag", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("(4323)1", "4323", "4323", "1", "SIG REQUIRED", "Signature required flag", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("(4324)2312310900", "4324", "4324", "2312310900", "NBEF DEL DT", "Not before delivery date/time", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("(4325)2312311700", "4325", "4325", "2312311700", "NAFT DEL DT", "Not after delivery date/time", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("(4326)231231", "4326", "4326", "231231", "REL DATE", "Release date", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("(7001)5310997032519", "7001", "7001", "5310997032519", "NSN", "NATO Stock Number (NSN)", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("(7003)2312312359", "7003", "7003", "2312312359", "EXPIRY TIME", "Expiration date and time", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("(7006)231231", "7006", "7006", "231231", "FIRST FREEZE DATE", "First freeze date", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("(7040)3PA_", "7040", "7040", "3PA_", "UIC+EXT", "GS1 UIC with Extension 1 and Importer index", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("(7241)05", "7241", "7241", "05", "AIDC MEDIA TYPE", "AIDC media type", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("(7250)20240214", "7250", "7250", "20240214", "DOB", "Date of birth", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("(7251)202402141743", "7251", "7251", "202402141743", "DOB TIME", "Date and time of birth", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("(7252)1", "7252", "7252", "1", "BIO SEX", "Biological sex", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("(7258)2/3", "7258", "7258", "2/3", "BIRTH SEQUENCE", "Baby birth sequence indicator", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("(8001)15000003056000", "8001", "8001", "15000003056000", "DIMENSIONS", "Roll products - width, length, core diameter, direction, splices", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("(8005)000150", "8005", "8005", "000150", "PRICE PER UNIT", "Price per unit of measure", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("(8006)050609175100040102", "8006", "8006", "050609175100040102", "ITIP", "Identification of an individual trade item (ITIP) piece", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("(8026)050609175100040102", "8026", "8026", "050609175100040102", "ITIP CONTENT", "Identification of pieces of a trade item (ITIP) contained in a logistic unit", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("(8111)0310", "8111", "8111", "0310", "POINTS", "Loyalty points of a coupon", "45", new string[0])]
        public async global::System.Threading.Tasks.Task ParenthesesInFixedLengthElementStrings(string input, string entity, string ai, string value, string dataValue, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("entity", entity);
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("value", value);
            argumentsOfScenario.Add("data value", dataValue);
            argumentsOfScenario.Add("description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parentheses in Fixed Length Element Strings", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.WhenAsync("the input to submitted to the parser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.ThenAsync(string.Format("the entity should be {0}", entity), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
  await testRunner.AndAsync(string.Format("the AI should be {0}", ai), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
  await testRunner.AndAsync(string.Format("the value should be {0}", value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
  await testRunner.AndAsync(string.Format("the data value should be {0}", dataValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
  await testRunner.AndAsync(string.Format("the description should be {0}", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
  await testRunner.AndAsync("the length of the value should be fixed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.AndAsync("there should be no errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Parentheses in Variable Length Element Strings")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ElementStrings")]
        [global::Xunit.TraitAttribute("Description", "Parentheses in Variable Length Element Strings")]
        [global::Xunit.InlineDataAttribute("(10)ABC123D", "10", "10", "ABC123D", "BATCH/LOT", "Batch or lot number", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("(21)7337203174393624", "21", "21", "7337203174393624", "SERIAL", "Serial number", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("(22)733AC720317439R3624", "22", "22", "733AC720317439R3624", "CPV", "Consumer product variant", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("(235)733AC720317439R3624", "235", "235", "733AC720317439R3624", "TPX", "Third Party Controlled, Serialised Extension of Global Trade Item Number (GTIN) (" +
            "TPX)", "49", new string[0])]
        [global::Xunit.InlineDataAttribute("(240)This+is+some+identifier+1234", "240", "240", "This+is+some+identifier+1234", "ADDITIONAL ID", "Additional product identification assigned by the manufacturer", "50", new string[0])]
        [global::Xunit.InlineDataAttribute("(241)This+is+some+part+no+1234", "241", "241", "This+is+some+part+no+1234", "CUST. PART No.", "Customer part number", "51", new string[0])]
        [global::Xunit.InlineDataAttribute("(242)1234", "242", "242", "1234", "MTO VARIANT", "Made-to-Order variation number", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("(243)This+is+some+pcn+123", "243", "243", "This+is+some+pcn+123", "PCN", "Packaging component number", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("(250)733AC720317439R3624", "250", "250", "733AC720317439R3624", "SECONDARY SERIAL", "Secondary serial number", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("(251)This+is+some+reference+1234", "251", "251", "This+is+some+reference+1234", "REF. TO SOURCE", "Reference to source entity", "55", new string[0])]
        [global::Xunit.InlineDataAttribute("(253)1234567890128733AC720317439R36", "253", "253", "1234567890128733AC720317439R36", "GDTI", "Global Document Type Identifier (GDTI)", "56", new string[0])]
        [global::Xunit.InlineDataAttribute("(254)Gln+Extension+254", "254", "254", "Gln+Extension+254", "GLN EXTENSION COMPONENT", "Global Location Number (GLN) extension component", "57", new string[0])]
        [global::Xunit.InlineDataAttribute("(255)1234567890128733720317439", "255", "255", "1234567890128733720317439", "GCN", "Global Coupon Number (GCN)", "58", new string[0])]
        [global::Xunit.InlineDataAttribute("(30)000999", "30", "30", "000999", "VAR. COUNT", "Variable count of items", "59", new string[0])]
        [global::Xunit.InlineDataAttribute("(37)12345678", "37", "37", "12345678", "COUNT", "Count of trade items or trade item pieces contained in a logistic unit", "60", new string[0])]
        [global::Xunit.InlineDataAttribute("(400)1234567890", "400", "400", "1234567890", "ORDER NUMBER", "Customer\'s purchase order number", "61", new string[0])]
        [global::Xunit.InlineDataAttribute("(401)506091751123456", "401", "401", "506091751123456", "GINC", "Global Identification Number for Consignment (GINC)", "62", new string[0])]
        [global::Xunit.InlineDataAttribute("(403)Routing+Code+1234", "403", "403", "Routing+Code+1234", "ROUTE", "Routing code", "63", new string[0])]
        [global::Xunit.InlineDataAttribute("(420)SE220PF", "420", "420", "SE220PF", "SHIP TO POST", "Ship-to / Deliver-to postal code within a single postal authority", "64", new string[0])]
        [global::Xunit.InlineDataAttribute("(421)826SE220PF", "421", "421", "826SE220PF", "SHIP TO POST", "Ship-to / Deliver-to postal code with three-digit ISO country code", "65", new string[0])]
        [global::Xunit.InlineDataAttribute("(423)826", "423", "423", "826", "COUNTRY - INITIAL PROCESS", "Country of initial processing", "66", new string[0])]
        [global::Xunit.InlineDataAttribute("(425)826", "425", "425", "826", "COUNTRY - DISASSEMBLY", "Country of disassembly", "67", new string[0])]
        [global::Xunit.InlineDataAttribute("(427)ENG", "427", "427", "ENG", "ORIGIN SUBDIVISION", "Country subdivision of origin code for a trade item", "68", new string[0])]
        [global::Xunit.InlineDataAttribute("(4300)Acme+Corp", "4300", "4300", "Acme+Corp", "SHIP TO COMP", "Ship-to / Deliver-to Company name", "69", new string[0])]
        [global::Xunit.InlineDataAttribute("(4301)John+Smith", "4301", "4301", "John+Smith", "SHIP TO NAME", "Ship-to / Deliver-to contact name", "70", new string[0])]
        [global::Xunit.InlineDataAttribute("(4302)100+Acadia+Avenue", "4302", "4302", "100+Acadia+Avenue", "SHIP TO ADD1", "Ship-to / Deliver-to address line 1", "71", new string[0])]
        [global::Xunit.InlineDataAttribute("(4303)Noborough", "4303", "4303", "Noborough", "SHIP TO ADD2", "Ship-to / Deliver-to address line 2", "72", new string[0])]
        [global::Xunit.InlineDataAttribute("(4304)Lower+District", "4304", "4304", "Lower+District", "SHIP TO SUB", "Ship-to / Deliver-to suburb", "73", new string[0])]
        [global::Xunit.InlineDataAttribute("(4305)Anytown", "4305", "4305", "Anytown", "SHIP TO LOC", "Ship-to / Deliver-to locality", "74", new string[0])]
        [global::Xunit.InlineDataAttribute("(4306)United+Kingdom", "4306", "4306", "United+Kingdom", "SHIP TO REG", "Ship-to / Deliver-to region", "75", new string[0])]
        [global::Xunit.InlineDataAttribute("(4308)+32-2-788-78-00", "4308", "4308", "+32-2-788-78-00", "SHIP TO PHONE", "Ship-to / Deliver-to telephone number", "76", new string[0])]
        [global::Xunit.InlineDataAttribute("(4310)Acme+Corp", "4310", "4310", "Acme+Corp", "RTN TO COMP", "Return-to company name", "77", new string[0])]
        [global::Xunit.InlineDataAttribute("(4311)John+Smith", "4311", "4311", "John+Smith", "RTN TO NAME", "Return-to contact name", "78", new string[0])]
        [global::Xunit.InlineDataAttribute("(4312)100+Acadia+Avenue", "4312", "4312", "100+Acadia+Avenue", "RTN TO ADD1", "Return-to address line 1", "79", new string[0])]
        [global::Xunit.InlineDataAttribute("(4313)Noborough", "4313", "4313", "Noborough", "RTN TO ADD2", "Return-to address line 2", "80", new string[0])]
        [global::Xunit.InlineDataAttribute("(4314)Lower+District", "4314", "4314", "Lower+District", "RTN TO SUB", "Return-to suburb", "81", new string[0])]
        [global::Xunit.InlineDataAttribute("(4315)Anytown", "4315", "4315", "Anytown", "RTN TO LOC", "Return-to locality", "82", new string[0])]
        [global::Xunit.InlineDataAttribute("(4316)United+Kingdom", "4316", "4316", "United+Kingdom", "RTN TO REG", "Return-to region", "83", new string[0])]
        [global::Xunit.InlineDataAttribute("(4318)SE220PF", "4318", "4318", "SE220PF", "RTN TO POST", "Return-to postal code", "84", new string[0])]
        [global::Xunit.InlineDataAttribute("(4319)+32-2-788-78-00", "4319", "4319", "+32-2-788-78-00", "RTN TO PHONE", "Return-to telephone number", "85", new string[0])]
        [global::Xunit.InlineDataAttribute("(4320)Service+code+description+12345", "4320", "4320", "Service+code+description+12345", "SRV DESCRIPTION", "Service code description", "86", new string[0])]
        [global::Xunit.InlineDataAttribute("(4330)023020", "4330", "4330", "023020", "MAX TEMP F", "Maximum temperature in Fahrenheit", "87", new string[0])]
        [global::Xunit.InlineDataAttribute("(4331)000090", "4331", "4331", "000090", "MAX TEMP C", "Maximum temperature in Celsius", "88", new string[0])]
        [global::Xunit.InlineDataAttribute("(4332)023020", "4332", "4332", "023020", "MIN TEMP F", "Minimum temperature in Fahrenheit", "89", new string[0])]
        [global::Xunit.InlineDataAttribute("(4333)000090", "4333", "4333", "000090", "MIN TEMP C", "Minimum temperature in Celsius", "90", new string[0])]
        [global::Xunit.InlineDataAttribute("(4330)000250-", "4330", "4330", "000250-", "MAX TEMP F", "Maximum temperature in Fahrenheit", "91", new string[0])]
        [global::Xunit.InlineDataAttribute("(4331)001000-", "4331", "4331", "001000-", "MAX TEMP C", "Maximum temperature in Celsius", "92", new string[0])]
        [global::Xunit.InlineDataAttribute("(4332)000250-", "4332", "4332", "000250-", "MIN TEMP F", "Minimum temperature in Fahrenheit", "93", new string[0])]
        [global::Xunit.InlineDataAttribute("(4333)001000-", "4333", "4333", "001000-", "MIN TEMP C", "Minimum temperature in Celsius", "94", new string[0])]
        [global::Xunit.InlineDataAttribute("(7002)44932211340000145100", "7002", "7002", "44932211340000145100", "MEAT CUT", "UNECE meat carcasses and cuts classification", "95", new string[0])]
        [global::Xunit.InlineDataAttribute("(7004)3001", "7004", "7004", "3001", "ACTIVE POTENCY", "Active potency", "96", new string[0])]
        [global::Xunit.InlineDataAttribute("(7005)27.6.b.1", "7005", "7005", "27.6.b.1", "CATCH AREA", "Catch area", "97", new string[0])]
        [global::Xunit.InlineDataAttribute("(7007)230801230831", "7007", "7007", "230801230831", "HARVEST DATE", "Harvest date", "98", new string[0])]
        [global::Xunit.InlineDataAttribute("(7008)BWQ", "7008", "7008", "BWQ", "AQUATIC SPECIES", "Species for fishery purposes", "99", new string[0])]
        [global::Xunit.InlineDataAttribute("(7009)01.1.1", "7009", "7009", "01.1.1", "FISHING GEAR TYPE", "Fishing gear type", "100", new string[0])]
        [global::Xunit.InlineDataAttribute("(7010)01", "7010", "7010", "01", "PROD METHOD", "Production method", "101", new string[0])]
        [global::Xunit.InlineDataAttribute("(7011)2312311200", "7011", "7011", "2312311200", "TEST BY DATE", "Test by date", "102", new string[0])]
        [global::Xunit.InlineDataAttribute("(7020)ABC123DE", "7020", "7020", "ABC123DE", "REFURB LOT", "Refurbishment lot ID", "103", new string[0])]
        [global::Xunit.InlineDataAttribute("(7021)Functional+status+01", "7021", "7021", "Functional+status+01", "FUNC STAT", "Functional status", "104", new string[0])]
        [global::Xunit.InlineDataAttribute("(7022)Revision+status+01", "7022", "7022", "Revision+status+01", "REV STAT", "Revision status", "105", new string[0])]
        [global::Xunit.InlineDataAttribute("(7023)506091751ASSET+0001", "7023", "7023", "506091751ASSET+0001", "GIAI – ASSEMBLY", "Global Individual Asset Identifier of an assembly", "106", new string[0])]
        [global::Xunit.InlineDataAttribute("(710)3675419", "710", "710", "3675419", "NHRN PZN", "National Healthcare Reimbursement Number (NHRN) - Germany PZN", "107", new string[0])]
        [global::Xunit.InlineDataAttribute("(711)3400935974419", "711", "711", "3400935974419", "NHRN CIP", "National Healthcare Reimbursement Number (NHRN) - France CIP", "108", new string[0])]
        [global::Xunit.InlineDataAttribute("(712)384756.8", "712", "712", "384756.8", "NHRN CN", "National Healthcare Reimbursement Number (NHRN) - Spain CN", "109", new string[0])]
        [global::Xunit.InlineDataAttribute("(713)40056320000011", "713", "713", "40056320000011", "NHRN DRN", "National Healthcare Reimbursement Number (NHRN) - Brasil DRN", "110", new string[0])]
        [global::Xunit.InlineDataAttribute("(714)142199", "714", "714", "142199", "NHRN AIM", "National Healthcare Reimbursement Number (NHRN) - Portugal AIM", "111", new string[0])]
        [global::Xunit.InlineDataAttribute("(715)0777310502", "715", "715", "0777310502", "NHRN NDC", "National Healthcare Reimbursement Number (NHRN) - United States of America NDC", "112", new string[0])]
        [global::Xunit.InlineDataAttribute("(716)A012345676", "716", "716", "A012345676", "NHRN AIC", "National Healthcare Reimbursement Number (NHRN) – Italy AIC", "113", new string[0])]
        [global::Xunit.InlineDataAttribute("(717)052-20220012345", "717", "717", "052-20220012345", "NHRN SRN", "National Healthcare Reimbursement Number (NHRN) – Costa Rica Sanitary Register Nu" +
            "mber", "114", new string[0])]
        [global::Xunit.InlineDataAttribute("(7041)1A", "7041", "7041", "1A", "UFRGT UNIT TYPE", "UN/CEFACT freight unit type", "115", new string[0])]
        [global::Xunit.InlineDataAttribute("(7230)EMBABT-MED00108", "723", "7230", "EMBABT-MED00108", "CERT # s", "Certification reference", "116", new string[0])]
        [global::Xunit.InlineDataAttribute("(7240)CACZ885N2301E2", "7240", "7240", "CACZ885N2301E2", "PROTOCOL", "Protocol ID", "117", new string[0])]
        [global::Xunit.InlineDataAttribute("(7253)Doe", "7253", "7253", "Doe", "FAMILY NAME", "Family name of person", "118", new string[0])]
        [global::Xunit.InlineDataAttribute("(7254)John", "7254", "7254", "John", "GIVEN NAME", "Given name of person", "119", new string[0])]
        [global::Xunit.InlineDataAttribute("(7255)Junior", "7255", "7255", "Junior", "SUFFIX", "Name suffix of person", "120", new string[0])]
        [global::Xunit.InlineDataAttribute("(7256)Doe,John,Junior", "7256", "7256", "Doe,John,Junior", "FULL NAME", "Full name of person", "121", new string[0])]
        [global::Xunit.InlineDataAttribute("(7257)123+Main+St,+Anytown,+Anyregion,+12345", "7257", "7257", "123+Main+St,+Anytown,+Anyregion,+12345", "PERSON ADDR", "Address of person", "122", new string[0])]
        [global::Xunit.InlineDataAttribute("(7259)Alice+Betty", "7259", "7259", "Alice+Betty", "BABY", "Baby of family name", "123", new string[0])]
        [global::Xunit.InlineDataAttribute("(8002)RF1DB6K177Y", "8002", "8002", "RF1DB6K177Y", "CMT No.", "Cellular mobile telephone identifier", "124", new string[0])]
        [global::Xunit.InlineDataAttribute("(8003)0506091751000434B1UL09036", "8003", "8003", "0506091751000434B1UL09036", "GRAI", "Global Returnable Asset Identifier (GRAI)", "125", new string[0])]
        [global::Xunit.InlineDataAttribute("(8004)5060917ASSET+0001", "8004", "8004", "5060917ASSET+0001", "GIAI", "Global Individual Asset Identifier (GIAI)", "126", new string[0])]
        [global::Xunit.InlineDataAttribute("(8008)231231142652", "8008", "8008", "231231142652", "PROD TIME", "Date and time of production", "127", new string[0])]
        [global::Xunit.InlineDataAttribute("(8009)01190531", "8009", "8009", "01190531", "OPTSEN", "Optically readable sensor indicator", "128", new string[0])]
        [global::Xunit.InlineDataAttribute("(8010)506091751DR4529P327", "8010", "8010", "506091751DR4529P327", "CPID", "Component/Part Identifier (CPID)", "129", new string[0])]
        [global::Xunit.InlineDataAttribute("(8011)422393761701", "8011", "8011", "422393761701", "CPID SERIAL", "Component/Part Identifier serial number", "130", new string[0])]
        [global::Xunit.InlineDataAttribute("(8012)15.0.4701.1001", "8012", "8012", "15.0.4701.1001", "VERSION", "Software version", "131", new string[0])]
        [global::Xunit.InlineDataAttribute("(8013)1987654Ad4X4bL5ttr2310c2K", "8013", "8013", "1987654Ad4X4bL5ttr2310c2K", "GMN", "Global Model Number (GMN)", "132", new string[0])]
        [global::Xunit.InlineDataAttribute("(8014)1987654Ad4X4bL5ttr2310c2K", "8014", "8014", "1987654Ad4X4bL5ttr2310c2K", "MUDI", "Highly Individualised Device Registration Identifier (HIDRI)", "133", new string[0])]
        [global::Xunit.InlineDataAttribute("(8019)00499427", "8019", "8019", "00499427", "SRIN", "Service Relation Instance Number (SRIN)", "134", new string[0])]
        [global::Xunit.InlineDataAttribute("(8020)000B231297726310000", "8020", "8020", "000B231297726310000", "REF No.", "Payment slip reference number", "135", new string[0])]
        [global::Xunit.InlineDataAttribute("(8030)417033192221743411860869815257112294233854053860719420698643236658923698457" +
            "81264435120798=", "8030", "8030", "417033192221743411860869815257112294233854053860719420698643236658923698457812644" +
            "35120798=", "DIGSIG", "Digital Signature (DigSig)", "136", new string[0])]
        [global::Xunit.InlineDataAttribute("(8040)490154203237518", "8040", "8040", "490154203237518", "IMEI", "International Mobile Equipment Identity (IMEI)", "137", new string[0])]
        [global::Xunit.InlineDataAttribute("(8041)356938035643809", "8041", "8041", "356938035643809", "IMEI2", "International Mobile Equipment Identity 2 (IMEI2)", "138", new string[0])]
        [global::Xunit.InlineDataAttribute("(8042)89033023456789012345678901234567", "8042", "8042", "89033023456789012345678901234567", "ESIM", "Embedded SIM", "139", new string[0])]
        [global::Xunit.InlineDataAttribute("(8043)8944500101234567890", "8043", "8043", "8944500101234567890", "PSIM", "Physical SIM", "140", new string[0])]
        [global::Xunit.InlineDataAttribute("(8110)106141416543213500110000310123196000", "8110", "8110", "106141416543213500110000310123196000", "-", "Coupon code identification for use in North America", "141", new string[0])]
        [global::Xunit.InlineDataAttribute("(8112)106141416543213500110000310123196000", "8112", "8112", "106141416543213500110000310123196000", "-", "Positive offer file coupon code identification for use in North America", "142", new string[0])]
        [global::Xunit.InlineDataAttribute("(8200)https://acme.com/", "8200", "8200", "https://acme.com/", "PRODUCT URL", "Extended packaging URL", "143", new string[0])]
        [global::Xunit.InlineDataAttribute("(90)Some+information+1234", "90", "90", "Some+information+1234", "INTERNAL", "Information mutually agreed between trading partners", "144", new string[0])]
        [global::Xunit.InlineDataAttribute("(91)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "91", "91", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "145", new string[0])]
        [global::Xunit.InlineDataAttribute("(92)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "92", "92", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "146", new string[0])]
        [global::Xunit.InlineDataAttribute("(93)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "93", "93", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "147", new string[0])]
        [global::Xunit.InlineDataAttribute("(94)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "94", "94", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "148", new string[0])]
        [global::Xunit.InlineDataAttribute("(95)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "95", "95", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "149", new string[0])]
        [global::Xunit.InlineDataAttribute("(96)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "96", "96", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "150", new string[0])]
        [global::Xunit.InlineDataAttribute("(97)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "97", "97", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "151", new string[0])]
        [global::Xunit.InlineDataAttribute("(98)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "98", "98", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "152", new string[0])]
        [global::Xunit.InlineDataAttribute("(99)The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "99", "99", "The+quick+brown+fox+jumped+over+the+lazy+dog\'s+back+01234567890", "INTERNAL", "Company internal information", "153", new string[0])]
        public async global::System.Threading.Tasks.Task ParenthesesInVariableLengthElementStrings(string input, string entity, string ai, string value, string dataValue, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("entity", entity);
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("value", value);
            argumentsOfScenario.Add("data value", dataValue);
            argumentsOfScenario.Add("description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parentheses in Variable Length Element Strings", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
 await testRunner.WhenAsync("the input to submitted to the parser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
 await testRunner.ThenAsync(string.Format("the entity should be {0}", entity), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
  await testRunner.AndAsync(string.Format("the AI should be {0}", ai), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
  await testRunner.AndAsync(string.Format("the value should be {0}", value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
  await testRunner.AndAsync(string.Format("the data value should be {0}", dataValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
  await testRunner.AndAsync(string.Format("the description should be {0}", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
  await testRunner.AndAsync("the length of the value should be variable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
  await testRunner.AndAsync("there should be no errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Parentheses in Fixed Length Element Strings with Inverse Exponent")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ElementStrings")]
        [global::Xunit.TraitAttribute("Description", "Parentheses in Fixed Length Element Strings with Inverse Exponent")]
        [global::Xunit.InlineDataAttribute("(3102)123456", "310", "3102", "2", "123456", "NET WEIGHT (kg)", "Net weight, kilograms (variable measure trade item)", "154", new string[0])]
        [global::Xunit.InlineDataAttribute("(3112)123456", "311", "3112", "2", "123456", "LENGTH (m)", "Length or first dimension, metres (variable measure trade item)", "155", new string[0])]
        [global::Xunit.InlineDataAttribute("(3122)123456", "312", "3122", "2", "123456", "WIDTH (m)", "Width, diameter, or second dimension, metres (variable measure trade item)", "156", new string[0])]
        [global::Xunit.InlineDataAttribute("(3132)123456", "313", "3132", "2", "123456", "HEIGHT (m)", "Depth, thickness, height, or third dimension, metres (variable measure trade item" +
            ")", "157", new string[0])]
        [global::Xunit.InlineDataAttribute("(3142)123456", "314", "3142", "2", "123456", "AREA (m²)", "Area, square metres (variable measure trade item)", "158", new string[0])]
        [global::Xunit.InlineDataAttribute("(3152)123456", "315", "3152", "2", "123456", "NET VOLUME (l)", "Net volume, litres (variable measure trade item)", "159", new string[0])]
        [global::Xunit.InlineDataAttribute("(3162)123456", "316", "3162", "2", "123456", "NET VOLUME (m³)", "Net volume, cubic metres (variable measure trade item)", "160", new string[0])]
        [global::Xunit.InlineDataAttribute("(3202)123456", "320", "3202", "2", "123456", "NET WEIGHT (lb)", "Net weight, pounds (variable measure trade item)", "161", new string[0])]
        [global::Xunit.InlineDataAttribute("(3212)123456", "321", "3212", "2", "123456", "LENGTH (i)", "Length or first dimension, inches (variable measure trade item)", "162", new string[0])]
        [global::Xunit.InlineDataAttribute("(3222)123456", "322", "3222", "2", "123456", "LENGTH (f)", "Length or first dimension, feet (variable measure trade item)", "163", new string[0])]
        [global::Xunit.InlineDataAttribute("(3232)123456", "323", "3232", "2", "123456", "LENGTH (y)", "Length or first dimension, yards (variable measure trade item)", "164", new string[0])]
        [global::Xunit.InlineDataAttribute("(3242)123456", "324", "3242", "2", "123456", "WIDTH (i)", "Width, diameter, or second dimension, inches (variable measure trade item)", "165", new string[0])]
        [global::Xunit.InlineDataAttribute("(3252)123456", "325", "3252", "2", "123456", "WIDTH (f)", "Width, diameter, or second dimension, feet (variable measure trade item)", "166", new string[0])]
        [global::Xunit.InlineDataAttribute("(3262)123456", "326", "3262", "2", "123456", "WIDTH (y)", "Width, diameter, or second dimension, yards (variable measure trade item)", "167", new string[0])]
        [global::Xunit.InlineDataAttribute("(3272)123456", "327", "3272", "2", "123456", "HEIGHT (i)", "Depth, thickness, height, or third dimension, inches (variable measure trade item" +
            ")", "168", new string[0])]
        [global::Xunit.InlineDataAttribute("(3282)123456", "328", "3282", "2", "123456", "HEIGHT (f)", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "169", new string[0])]
        [global::Xunit.InlineDataAttribute("(3292)123456", "329", "3292", "2", "123456", "HEIGHT (y)", "Depth, thickness, height, or third dimension, yards (variable measure trade item)" +
            "", "170", new string[0])]
        [global::Xunit.InlineDataAttribute("(3302)123456", "330", "3302", "2", "123456", "GROSS WEIGHT (kg)", "Logistic weight, kilograms", "171", new string[0])]
        [global::Xunit.InlineDataAttribute("(3312)123456", "331", "3312", "2", "123456", "LENGTH (m), log", "Length or first dimension, metres", "172", new string[0])]
        [global::Xunit.InlineDataAttribute("(3322)123456", "332", "3322", "2", "123456", "WIDTH (m), log", "Width, diameter, or second dimension, metres", "173", new string[0])]
        [global::Xunit.InlineDataAttribute("(3332)123456", "333", "3332", "2", "123456", "HEIGHT (m), log", "Depth, thickness, height, or third dimension, metres", "174", new string[0])]
        [global::Xunit.InlineDataAttribute("(3342)123456", "334", "3342", "2", "123456", "AREA (m²), log", "Area, square metres", "175", new string[0])]
        [global::Xunit.InlineDataAttribute("(3352)123456", "335", "3352", "2", "123456", "VOLUME (l), log", "Logistic volume, litres", "176", new string[0])]
        [global::Xunit.InlineDataAttribute("(3362)123456", "336", "3362", "2", "123456", "VOLUME (m³), log", "Logistic volume, cubic metres", "177", new string[0])]
        [global::Xunit.InlineDataAttribute("(3372)123456", "337", "3372", "2", "123456", "KG PER m²", "Kilograms per square metre", "178", new string[0])]
        [global::Xunit.InlineDataAttribute("(3402)123456", "340", "3402", "2", "123456", "GROSS WEIGHT (lb)", "Logistic weight, pounds", "179", new string[0])]
        [global::Xunit.InlineDataAttribute("(3412)123456", "341", "3412", "2", "123456", "LENGTH (i), log", "Length or first dimension, inches", "180", new string[0])]
        [global::Xunit.InlineDataAttribute("(3422)123456", "342", "3422", "2", "123456", "LENGTH (f), log", "Length or first dimension, feet", "181", new string[0])]
        [global::Xunit.InlineDataAttribute("(3432)123456", "343", "3432", "2", "123456", "LENGTH (y), log", "Length or first dimension, yards", "182", new string[0])]
        [global::Xunit.InlineDataAttribute("(3442)123456", "344", "3442", "2", "123456", "WIDTH (i), log", "Width, diameter, or second dimension, inches", "183", new string[0])]
        [global::Xunit.InlineDataAttribute("(3452)123456", "345", "3452", "2", "123456", "WIDTH (f), log", "Width, diameter, or second dimension, feet", "184", new string[0])]
        [global::Xunit.InlineDataAttribute("(3462)123456", "346", "3462", "2", "123456", "WIDTH (y), log", "Width, diameter, or second dimension, yard", "185", new string[0])]
        [global::Xunit.InlineDataAttribute("(3472)123456", "347", "3472", "2", "123456", "HEIGHT (i), log", "Depth, thickness, height, or third dimension, inches", "186", new string[0])]
        [global::Xunit.InlineDataAttribute("(3482)123456", "348", "3482", "2", "123456", "HEIGHT (f), log", "Depth, thickness, height, or third dimension, feet", "187", new string[0])]
        [global::Xunit.InlineDataAttribute("(3492)123456", "349", "3492", "2", "123456", "HEIGHT (y), log", "Depth, thickness, height, or third dimension, yards", "188", new string[0])]
        [global::Xunit.InlineDataAttribute("(3502)123456", "350", "3502", "2", "123456", "AREA (i²)", "Area, square inches (variable measure trade item)", "189", new string[0])]
        [global::Xunit.InlineDataAttribute("(3512)123456", "351", "3512", "2", "123456", "AREA (f²)", "Area, square feet (variable measure trade item)", "190", new string[0])]
        [global::Xunit.InlineDataAttribute("(3522)123456", "352", "3522", "2", "123456", "AREA (y²)", "Area, square yards (variable measure trade item)", "191", new string[0])]
        [global::Xunit.InlineDataAttribute("(3532)123456", "353", "3532", "2", "123456", "AREA (i²), log", "Area, square inches", "192", new string[0])]
        [global::Xunit.InlineDataAttribute("(3542)123456", "354", "3542", "2", "123456", "AREA (f²), log", "Area, square feet", "193", new string[0])]
        [global::Xunit.InlineDataAttribute("(3552)123456", "355", "3552", "2", "123456", "AREA (y²), log", "Area, square yards", "194", new string[0])]
        [global::Xunit.InlineDataAttribute("(3562)123456", "356", "3562", "2", "123456", "NET WEIGHT (tr oz)", "Net weight, troy ounces (variable measure trade item)", "195", new string[0])]
        [global::Xunit.InlineDataAttribute("(3572)123456", "357", "3572", "2", "123456", "NET VOLUME (oz)", "Net weight (or volume), ounces (variable measure trade item)", "196", new string[0])]
        [global::Xunit.InlineDataAttribute("(3602)123456", "360", "3602", "2", "123456", "NET VOLUME (qt (US))", "Net volume, quarts (variable measure trade item)", "197", new string[0])]
        [global::Xunit.InlineDataAttribute("(3612)123456", "361", "3612", "2", "123456", "NET VOLUME (gal (US))", "Net volume, gallons U.S. (variable measure trade item)", "198", new string[0])]
        [global::Xunit.InlineDataAttribute("(3622)123456", "362", "3622", "2", "123456", "VOLUME (qt (US)), log", "Logistic volume, quarts", "199", new string[0])]
        [global::Xunit.InlineDataAttribute("(3632)123456", "363", "3632", "2", "123456", "VOLUME (gal (US)), log", "Logistic volume, gallons U.S.", "200", new string[0])]
        [global::Xunit.InlineDataAttribute("(3642)123456", "364", "3642", "2", "123456", "VOLUME (i³)", "Net volume, cubic inches (variable measure trade item)", "201", new string[0])]
        [global::Xunit.InlineDataAttribute("(3652)123456", "365", "3652", "2", "123456", "VOLUME (f³)", "Net volume, cubic feet (variable measure trade item)", "202", new string[0])]
        [global::Xunit.InlineDataAttribute("(3662)123456", "366", "3662", "2", "123456", "VOLUME (y³)", "Net volume, cubic yards (variable measure trade item)", "203", new string[0])]
        [global::Xunit.InlineDataAttribute("(3672)123456", "367", "3672", "2", "123456", "VOLUME (i³), log", "Logistic volume, cubic inches", "204", new string[0])]
        [global::Xunit.InlineDataAttribute("(3682)123456", "368", "3682", "2", "123456", "VOLUME (f³), log", "Logistic volume, cubic feet", "205", new string[0])]
        [global::Xunit.InlineDataAttribute("(3692)123456", "369", "3692", "2", "123456", "VOLUME (y³), log", "Logistic volume, cubic yards", "206", new string[0])]
        [global::Xunit.InlineDataAttribute("(3942)1234", "394", "3942", "2", "1234", "PRCNT OFF", "Percentage discount of a coupon", "207", new string[0])]
        [global::Xunit.InlineDataAttribute("(3952)123456", "395", "3952", "2", "123456", "PRICE/UoM", "Amount payable per unit of measure single monetary area (variable measure trade i" +
            "tem)", "208", new string[0])]
        public async global::System.Threading.Tasks.Task ParenthesesInFixedLengthElementStringsWithInverseExponent(string input, string entity, string ai, string inverseExponent, string value, string dataValue, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("entity", entity);
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("inverse exponent", inverseExponent);
            argumentsOfScenario.Add("value", value);
            argumentsOfScenario.Add("data value", dataValue);
            argumentsOfScenario.Add("description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parentheses in Fixed Length Element Strings with Inverse Exponent", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 249
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 250
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 251
 await testRunner.WhenAsync("the input to submitted to the parser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 252
 await testRunner.ThenAsync(string.Format("the entity should be {0}", entity), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 253
  await testRunner.AndAsync(string.Format("the AI should be {0}", ai), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
  await testRunner.AndAsync(string.Format("the inverse exponent should be {0}", inverseExponent), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 255
  await testRunner.AndAsync(string.Format("the value should be {0}", value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
  await testRunner.AndAsync(string.Format("the data value should be {0}", dataValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
  await testRunner.AndAsync(string.Format("the description should be {0}", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
  await testRunner.AndAsync("the length of the value should be fixed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 259
  await testRunner.AndAsync("there should be no errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Parentheses in Variable Length Element Strings with Inverse Exponent")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ElementStrings")]
        [global::Xunit.TraitAttribute("Description", "Parentheses in Variable Length Element Strings with Inverse Exponent")]
        [global::Xunit.InlineDataAttribute("(3902)123456789012345", "390", "3902", "2", "123456789012345", "AMOUNT", "Amount payable or coupon value - Single monetary area", "209", new string[0])]
        [global::Xunit.InlineDataAttribute("(3912)826123456789012345", "391", "3912", "2", "826123456789012345", "AMOUNT", "Amount payable and ISO currency code", "210", new string[0])]
        [global::Xunit.InlineDataAttribute("(3922)123456789012345", "392", "3922", "2", "123456789012345", "PRICE", "Amount payable for a variable measure trade item - Single monetary area", "211", new string[0])]
        [global::Xunit.InlineDataAttribute("(3932)826123456789012345", "393", "3932", "2", "826123456789012345", "PRICE", "Amount payable for a variable measure trade item and ISO currency code", "212", new string[0])]
        public async global::System.Threading.Tasks.Task ParenthesesInVariableLengthElementStringsWithInverseExponent(string input, string entity, string ai, string inverseExponent, string value, string dataValue, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("entity", entity);
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("inverse exponent", inverseExponent);
            argumentsOfScenario.Add("value", value);
            argumentsOfScenario.Add("data value", dataValue);
            argumentsOfScenario.Add("description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parentheses in Variable Length Element Strings with Inverse Exponent", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 329
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 330
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 331
 await testRunner.WhenAsync("the input to submitted to the parser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 332
 await testRunner.ThenAsync(string.Format("the entity should be {0}", entity), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 333
  await testRunner.AndAsync(string.Format("the AI should be {0}", ai), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
  await testRunner.AndAsync(string.Format("the inverse exponent should be {0}", inverseExponent), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 335
  await testRunner.AndAsync(string.Format("the value should be {0}", value), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
  await testRunner.AndAsync(string.Format("the data value should be {0}", dataValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 337
  await testRunner.AndAsync(string.Format("the description should be {0}", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 338
  await testRunner.AndAsync("the length of the value should be variable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 339
  await testRunner.AndAsync("there should be no errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ElementStringsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ElementStringsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
