<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net7.0;net6.0;netstandard2.0</TargetFrameworks>
	<ActiveTargetFramework>net7.0</ActiveTargetFramework>
	<LangVersion>preview</LangVersion>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<PublishReadyToRun>true</PublishReadyToRun>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>GS1 AI Validating Parser</Title>
    <Copyright>© 2018-2025 Solidsoft Reply</Copyright>
    <Authors>cnayoung</Authors>
    <Company>Solidsoft Reply Ltd.</Company>
    <RepositoryUrl>https://github.com/Solidsoft-Reply/Solidsoft.Reply.Parsers.Gs1Ai</RepositoryUrl>
    <PackageProjectUrl>https://www.reply.com/solidsoft-reply/en/</PackageProjectUrl>
    <PackageIcon>Solidsoft Reply - LOGO Square_small.jpg</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageTags>gs1;ai;parser;barcode;datamatrix;qr;code-128</PackageTags>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	<PackageReleaseNotes>
		This release contains minor breaking changes as well as new functionality. Please check existing code carefully to ensure that it continues to work as expected after upgrading.

		The following changes were made in this release.

		1) Added support for new NHRN (Costa Rica Sanitary Register Number). AI 717 - see GSCN 25-199.

		2) Added support for new GS1 AIs for activation of mobile communication devices onto cellular networks. AIs 8040, 8041, 8042 and 8043 - see GSCN 25-047.

		3) Updated abbreviations for measures to UN ECE Recommendation 20 - see GSCN 25-081.

		4) Fixed an issue concerning detection of elements that are incorrectly terminated with an FNC1 character.

		5) Fixed an issue with enumeration of exceptions when calling ParseEx().
		
		6) Improved error handling to provide a more consistent approach to classifying errors as fatal or non-fatal.

		7) Rationalised error and warning numbers. This is a potentially breaking change if existing code relies on specific error number values.

		8) Consistent reporting of positions and offsets in resolved elements and exceptions.

		9) Consistent use of the term 'element' instead of 'entity' to align better with GS1 terminology. NB., this is a breaking change.

		10) Supplied missing translations for all official EU and EFTA languages.

		11) Added support for parsing mulitple element string sequences in a single call to Parse().

		12) Implemented data relationship rules for certain AIs as per GS1 General Specifications.

		13) Added support for parsing data elements represented is GS1 Human-Readable Information (HRI) format.

		14) Provided improved and expanded documentation for parser.

	</PackageReleaseNotes>
    <Description>
		A comprehensive validating parser for GS1 Application Identifiers (AIs).

		Latest Release Notes:
		--------------
		$(PackageReleaseNotes)
	</Description>
	<Version>2.0.0</Version>
	<AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	<NeutralLanguage>en</NeutralLanguage>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <CodeAnalysisRuleSet>$(SolutionDir)/StyleCopAnalyzersDefault.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Solidsoft Reply - LOGO Square_small.jpg" />
    <None Remove="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\DEVELOPER-NOTICE.txt" Link="Notices\DEVELOPER-NOTICE.txt" />
  </ItemGroup>

	<ItemGroup>
		<None Include="../LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="../README.md" Pack="true" PackagePath="" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Only add System.Memory for netstandard2.0 -->
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
	
  <ItemGroup>
    <Resource Include="Solidsoft Reply - LOGO Square_small.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Gs1ApplicationIdentifier.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Gs1CountryCode.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.es.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
    </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.fr.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.de.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
    <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.it.resx">
	    <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
    </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.bg.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.cs.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.da.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.el.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.et.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.fi.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.ga.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.hr.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.hu.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.is.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.lt.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.lv.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.mt.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.nl.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.no.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.pl.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.pt.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.ro.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.sk.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.sl.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.sv.resx">
      <DependentUpon>Gs1ApplicationIdentifier.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1ApplicationIdentifier.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Gs1ApplicationIdentifier.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Gs1CountryCode.es.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
    </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.fr.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.de.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
    <EmbeddedResource Update="Properties\Gs1CountryCode.it.resx">
	    <DependentUpon>Gs1CountryCode.resx</DependentUpon>
    </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.bg.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.cs.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.da.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.el.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.et.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.fi.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.ga.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.hr.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.hu.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.is.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.lt.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.lv.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.mt.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.nl.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.no.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.pl.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.pt.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.ro.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.sk.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.sl.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Gs1CountryCode.sv.resx">
      <DependentUpon>Gs1CountryCode.resx</DependentUpon>
	  </EmbeddedResource>
    <EmbeddedResource Update="Properties\Gs1CountryCode.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Gs1CountryCode.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources - Copy.de.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.de.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.es.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.fr.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.it.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.bg.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	  <EmbeddedResource Update="Properties\Resources.cs.resx">
    <DependentUpon>Resources.resx</DependentUpon>
	  </EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.da.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.el.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.et.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.fi.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.ga.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.hr.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.hu.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.is.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.lt.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.lv.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.mt.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.nl.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.no.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.pl.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.pt.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.ro.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.sk.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.sl.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.sv.resx">
      <DependentUpon>Resources.resx</DependentUpon>
	</EmbeddedResource>
	<EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Link="README.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Solidsoft.Reply.Parsers.Common\Solidsoft.Reply.Parsers.Common\Solidsoft.Reply.Parsers.Common.csproj" />
  </ItemGroup>

</Project>
