// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Solidsoft.Reply.Parsers.Gs1Ai.Tests.Net7.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DataRelationshipsFeature : object, global::Xunit.IClassFixture<DataRelationshipsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "DataRelationships", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DataRelationships.feature"
#line hidden
        
        public DataRelationshipsFeature(DataRelationshipsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DataRelationships.feature.ndjson", 514);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Detect invalid data relationships")]
        [global::Xunit.TraitAttribute("FeatureTitle", "DataRelationships")]
        [global::Xunit.TraitAttribute("Description", "Detect invalid data relationships")]
        [global::Xunit.InlineDataAttribute("01", "02", "0109506000134376023506091751986210ABC123[GS]17311231", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("01", "03", "0109506000134376033506091751986210ABC123[GS]17311231", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("01", "37", "010950600013437637144[GS]10ABC123[GS]17311231", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("03", "37", "030950600013437637144[GS]10ABC123[GS]173112311", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("01", "255", "01095060001343762555060917519861[GS]10ABC123[GS]17311231", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("03", "02", "0309506000134376023506091751986210ABC123[GS]17311231", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("21", "235", "2351ABC36610835978537[GS]010950600013437610ABC123[GS]173112312123560917519861", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("420", "421", "010950600013437610ABC123[GS]420SW23TP[GS]421826SW23TP", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("421", "4307", "010950600013437610ABC123[GS]421826SW23TP[GS]4307GB", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("422", "426", "010950600013437610ABC123[GS]422826[GS]426826", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("423", "426", "010950600013437610ABC123[GS]423826250276[GS]426826", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("424", "426", "010950600013437610ABC123[GS]424826[GS]426826", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("425", "426", "010950600013437610ABC123[GS]425826250276[GS]426826", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("3900", "3910", "01095060001343763900123[GS]3910826123[GS]802036641008056438[GS]41509506000134376", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("3900", "3941", "3900123[GS]39410055[GS]25509506000134376", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("3900", "8111", "3900123[GS]81110125[GS]25509506000134376", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("3920", "3930", "01095060001343763920123[GS]3930826123[GS]30144", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("3920", "3953", "01095060001343763920123[GS]3953123456[GS]30144", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("3940", "8111", "39400010[GS]81110125[GS]25509506000134376", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("3953", "8005", "01095060001343763953123456[GS]8005001234[GS]30144", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("3953", "3920", "01095060001343763953123456[GS]3920123[GS]30144", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("3953", "3930", "01095060001343763953123456[GS]3930826123[GS]30144", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("4330", "4331", "009506000984275650204330000250-[GS]4331001917-", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("4332", "4333", "009506000984275650204332000250-[GS]4333001917-", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("7250", "7251", "725019630304[GS]7251196303040104[GS]8018950600098427565020", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("7256", "7253", "7256JOHN+SMITH+JR[GS]7253SMITH[GS]8018950600098427565020", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("7256", "7254", "7256JOHN+SMITH+JR[GS]7254JOHN[GS]8018950600098427565020", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("7256", "7255", "7256JOHN+SMITH+JR[GS]7255JR[GS]8018950600098427565020", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("7256", "7259", "7256JOHN+SMITH+JR[GS]7259SMITH+BABY+BOY[GS]8018950600098427565020", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("7259", "7253", "7259SMITH+BABY+BOY[GS]7253SMITH[GS]8018950600098427565020", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("7259", "7254", "7259SMITH+BABY+BOY[GS]7254JOHN[GS]8018950600098427565020", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("7259", "7255", "7259SMITH+BABY+BOY[GS]7255JR[GS]8018950600098427565020", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("7259", "7256", "7259SMITH+BABY+BOY[GS]7256JOHN+SMITH+JR[GS]8018950600098427565020", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("8006", "01", "01095060001343768006095060001343760310", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("8006", "37", "800609506000134[GS]3760310[GS]3710", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("8018", "8017", "8017950600098427565020[GS]8018950600098427565020", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("8026", "02", "0095060009842756502002350609175198623710[GS]8026095060001343760310", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("8026", "8006", "009506000984275650208006095060001343760310[GS]3710[GS]8026095060001343760310", "37", new string[0])]
        public async global::System.Threading.Tasks.Task DetectInvalidDataRelationships(string ai1, string ai2, string input, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ai1", ai1);
            argumentsOfScenario.Add("ai2", ai2);
            argumentsOfScenario.Add("input", input);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Detect invalid data relationships", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.WhenAsync("the input to submitted to the parser and data relationship tests are required", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.ThenAsync(string.Format("we should detect AI {0}", ai1), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
 await testRunner.AndAsync("the errors should include a fatal 2201 error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Detect invalid duplicate AI data relationships")]
        [global::Xunit.TraitAttribute("FeatureTitle", "DataRelationships")]
        [global::Xunit.TraitAttribute("Description", "Detect invalid duplicate AI data relationships")]
        [global::Xunit.InlineDataAttribute("01", "01", "0109506000134376013506091751986210ABC123[GS]17311231", "38", new string[0])]
        public async global::System.Threading.Tasks.Task DetectInvalidDuplicateAIDataRelationships(string ai1, string ai2, string input, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ai1", ai1);
            argumentsOfScenario.Add("ai2", ai2);
            argumentsOfScenario.Add("input", input);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Detect invalid duplicate AI data relationships", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
 await testRunner.WhenAsync("the input to submitted to the parser and data relationship tests are required", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
 await testRunner.ThenAsync("the errors should include a fatal 2202 error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Detect invalid duplicate AI data relationships across multiple barcodes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "DataRelationships")]
        [global::Xunit.TraitAttribute("Description", "Detect invalid duplicate AI data relationships across multiple barcodes")]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231", "010950600013437610XYZ999[GS]17320531", "013506091751986210ABC123[GS]17311231", "39", new string[0])]
        public async global::System.Threading.Tasks.Task DetectInvalidDuplicateAIDataRelationshipsAcrossMultipleBarcodes(string barcode1, string barcode2, string barcode3, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("barcode1", barcode1);
            argumentsOfScenario.Add("barcode2", barcode2);
            argumentsOfScenario.Add("barcode3", barcode3);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Detect invalid duplicate AI data relationships across multiple barcodes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
    await testRunner.GivenAsync(string.Format("the input for barcode 1 is {0}", barcode1), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.AndAsync(string.Format("the input for barcode 2 is {0}", barcode2), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync(string.Format("the input for barcode 3 is {0}", barcode3), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.WhenAsync("the barcodes are submitted to the parser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
 await testRunner.ThenAsync("there should be invalid duplicate AI pairs", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Validate data relationships between multiple data elements")]
        [global::Xunit.TraitAttribute("FeatureTitle", "DataRelationships")]
        [global::Xunit.TraitAttribute("Description", "Validate data relationships between multiple data elements")]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313010", "01.VariableMeasure", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313100000010", "01.VariableMeasure", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("019950600013437910ABC123[GS]173112313010", "01.VariableMeasure", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("019950600013437910ABC123[GS]173112313100000010", "01.VariableMeasure", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("019950600013437910ABC123[GS]17311231800110000010010010", "01.VariableMeasure", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020029950600013437910ABC123[GS]173112313010[GS]3710", "01.VariableMeasure", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020029950600013437910ABC123[GS]1731123131000000103710", "01.VariableMeasure", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("019950600013437910ABC123[GS]1731123124223", "01.Custom", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("030950600013437624223[GS]8006950609175198640310", "", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502002350609175198623710", "", "49", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231", "", "50", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710", "", "51", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310", "", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]8026095060001343760310[GS]3710", "", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("030950600013437610ABC123", "", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]11251221", "", "55", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]13251221", "", "56", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]15260103", "", "57", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]16261102", "", "58", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17260103", "", "59", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]112512213710", "", "60", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]132512213710", "", "61", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]152601033710", "", "62", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]162611023710", "", "63", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]172601033710", "", "64", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]112512218006095060001343760310", "", "65", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]132512218006095060001343760310", "", "66", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]152601038006095060001343760310", "", "67", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]162611028006095060001343760310", "", "68", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]172601038006095060001343760310", "", "69", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]112512218026095060001343760310[GS]3710", "", "70", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]132512218026095060001343760310[GS]3710", "", "71", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]152601038026095060001343760310[GS]3710", "", "72", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]162611028026095060001343760310[GS]3710", "", "73", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]172601038026095060001343760310[GS]3710", "", "74", new string[0])]
        [global::Xunit.InlineDataAttribute("1225123180201438940A32[GS]4159506000134376", "", "75", new string[0])]
        [global::Xunit.InlineDataAttribute("172601032555060917519861", "17.Coupon", "76", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376200317311231", "", "77", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502002095060001343762003173112313710", "", "78", new string[0])]
        [global::Xunit.InlineDataAttribute("20038006095060001343760310", "", "79", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502020038026095060001343760310[GS]3710", "", "80", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112312149950304162", "", "81", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]2149950304162", "", "82", new string[0])]
        [global::Xunit.InlineDataAttribute("030950600013437610ABC123[GS]2149950304162", "", "83", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343762249950A304162", "", "84", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343762352351ABC36610835978537", "", "85", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437624049950A304162[GS]17311231", "", "86", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437624049950A304162[GS]173112313710", "", "87", new string[0])]
        [global::Xunit.InlineDataAttribute("24049950A304162[GS]8006095060001343760310", "", "88", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502024049950A304162[GS]8026095060001343760310[GS]3710", "", "89", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437624149950A304162[GS]17311231", "", "90", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437624149950A304162[GS]173112313710", "", "91", new string[0])]
        [global::Xunit.InlineDataAttribute("24149950A304162[GS]8006095060001343760310", "", "92", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502024149950A304162[GS]8026095060001343760310[GS]3710", "", "93", new string[0])]
        [global::Xunit.InlineDataAttribute("019950600013437924223[GS]17311231", "", "94", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020029950600013437924223[GS]173112313010[GS]3710", "", "95", new string[0])]
        [global::Xunit.InlineDataAttribute("24223[GS]8006995060001343790310", "", "96", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502024223[GS]8026995060001343790310[GS]3710", "", "97", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343762431ABC36610835978537", "", "98", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123125049950304162[GS]218801005795367", "", "99", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]25049950304162[GS]218801005795367", "", "100", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123125149950304162", "", "101", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]25149950304162", "", "102", new string[0])]
        [global::Xunit.InlineDataAttribute("254JJ429[GS]4149506000134376", "", "103", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123130100", "", "104", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]30100", "", "105", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313100000001", "", "106", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313100000001", "01.VariableMeasure", "107", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]3100000001", "", "108", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313200000001", "", "109", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313200000001", "01.VariableMeasure", "110", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]3200000001", "", "111", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313500000001", "", "112", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313500000001", "01.VariableMeasure", "113", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]3500000001", "", "114", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313600000001", "", "115", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313600000001", "01.VariableMeasure", "116", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]3600000001", "", "117", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020010950600013437610ABC123[GS]173112313330000001", "", "118", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313330000001", "", "119", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020010950600013437610ABC123[GS]173112313430000001", "", "120", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313430000001", "", "121", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020010950600013437610ABC123[GS]173112313530000001", "", "122", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313530000001", "", "123", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020010950600013437610ABC123[GS]173112313630000001", "", "124", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112313630000001", "", "125", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376337200145810ABC123[GS]17311231", "", "126", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437637144[GS]10ABC123", "", "127", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502010ABC123[GS]8026095060001343760310[GS]37144", "", "128", new string[0])]
        [global::Xunit.InlineDataAttribute("8020R470364122BJ5[GS]3902001458[GS]4159506000134376", "", "129", new string[0])]
        [global::Xunit.InlineDataAttribute("3902001458[GS]2555060917519861", "3902.CouponValue", "130", new string[0])]
        [global::Xunit.InlineDataAttribute("8020R470364122BJ5[GS]3912978001458[GS]4159506000134376", "", "131", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3922001458[GS]3010", "", "132", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3922001458[GS]3100000001", "", "133", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3922001458[GS]3200000001", "", "134", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3922001458[GS]3500000001", "", "135", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3922001458[GS]3600000001", "", "136", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3932978001458[GS]3010", "", "137", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3932978001458[GS]3100000001", "", "138", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3932978001458[GS]3200000001", "", "139", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3932978001458[GS]3500000001", "", "140", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3932978001458[GS]3600000001", "", "141", new string[0])]
        [global::Xunit.InlineDataAttribute("39400010[GS]2555060917519861", "", "142", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3952001458[GS]3010", "", "143", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3952001458[GS]3100000001", "", "144", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3952001458[GS]3200000001", "", "145", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3952001458[GS]3500000001", "", "146", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]3952001458[GS]3600000001", "", "147", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020403GBR4720045198", "", "148", new string[0])]
        [global::Xunit.InlineDataAttribute("8020R470364122BJ5[GS]4159506000134376", "", "149", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376422826[GS]17311231", "", "150", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376422826[GS]173112313710", "", "151", new string[0])]
        [global::Xunit.InlineDataAttribute("422826[GS]8006095060001343760310", "", "152", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020422826[GS]8026095060001343760310[GS]3710", "", "153", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231423826250276", "", "154", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]423826250276", "", "155", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231424826", "", "156", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]424826", "", "157", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231425826250276", "", "158", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437610ABC123[GS]173112313710[GS]425826250276", "", "159", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231426826", "", "160", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]426826", "", "161", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231422826[GS]427826", "", "162", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]422826[GS]427826", "", "163", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204300ACME+LIMITED", "", "164", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204301JOHN+SMITH", "", "165", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204302UNIT+5", "", "166", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204304UPPER+NETHERBY", "", "167", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204305WESTGATE", "", "168", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204306BILLINGSHIRE", "", "169", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204307GB", "", "170", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020430801379250388", "", "171", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204302UNIT+5[GS]4303ELM+STREET+BUSINESS+PARK", "", "172", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020430902790858483015297971", "", "173", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204310ACME+LIMITED", "", "174", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204311JOHN+SMITH", "", "175", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204312UNIT+5", "", "176", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204314UPPER+NETHERBY", "", "177", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204315WESTGATE", "", "178", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204316BILLINGSHIRE", "", "179", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204317GB", "", "180", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204318AA11AA", "", "181", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020431901379250388", "", "182", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204312UNIT+5[GS]4313ELM+STREET+BUSINESS+PARK", "", "183", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204320HANDLE+WITH+CARE", "", "184", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502043211", "", "185", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502043221", "", "186", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502043231", "", "187", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502043242512271300", "", "188", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502043252512271300", "", "189", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204326260131", "", "190", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204330023020", "", "191", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204331000090", "", "192", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204332023020", "", "193", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650204333000090", "", "194", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437670011005000739421[GS]17311231", "", "195", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020020950600013437670011005000739421[GS]173112313710", "", "196", new string[0])]
        [global::Xunit.InlineDataAttribute("70011005000739421[GS]8006095060001343760310", "", "197", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502070011005000739421[GS]8026095060001343760310[GS]3710", "", "198", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231700210164300153201040050", "", "199", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]700210164300153201040050", "", "200", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123170032603311200", "", "201", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]70032603311200", "", "202", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123170043107", "", "203", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231700527.8.e.2", "", "204", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]700527.8.e.2", "", "205", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317006251227", "", "206", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7006251227", "", "207", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317007250803250817", "", "208", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7007250803250817", "", "209", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317008BOH", "", "210", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7008BOH", "", "211", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231700909.31", "", "212", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]700909.31", "", "213", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231701001", "", "214", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]701001", "", "215", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123170112603151200", "", "216", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]70112603151200", "", "217", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317030826AB123C456", "", "218", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317031826AB123C456", "", "219", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317032826AB123C456", "", "220", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317033826AB123C456", "", "221", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317034826AB123C456", "", "222", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317035826AB123C456", "", "223", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317036826AB123C456", "", "224", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317037826AB123C456", "", "225", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317038826AB123C456", "", "226", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317039826AB123C456", "", "227", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7030826AB123C456", "", "228", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7031826AB123C456", "", "229", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7032826AB123C456", "", "230", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7033826AB123C456", "", "231", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7034826AB123C456", "", "232", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7035826AB123C456", "", "233", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7036826AB123C456", "", "234", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7037826AB123C456", "", "235", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7038826AB123C456", "", "236", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]7039826AB123C456", "", "237", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437671027580899", "", "238", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343767113400123456789", "", "239", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376712244137.8", "", "240", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343767131234567890123", "", "241", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343767145551643", "", "242", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437671500781150610", "", "243", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376716365820310", "", "244", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376717M-ES-20-00283", "", "245", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343767020ABC123[GS]173112314169506000134376", "", "246", new string[0])]
        [global::Xunit.InlineDataAttribute("7020ABC123[GS]8006095060001343760310[GS]4169506000134376", "", "247", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317021APPROVED2512", "", "248", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]7021APPROVED2512", "", "249", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317021APPROVED2512[GS]70224.178", "", "250", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]7021APPROVED2512[GS]70224.178", "", "251", new string[0])]
        [global::Xunit.InlineDataAttribute("0095060009842756502070414A", "", "252", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317230EMAB123C456", "", "253", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317231EMAB123C456", "", "254", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317232EMAB123C456", "", "255", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317233EMAB123C456", "", "256", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317234EMAB123C456", "", "257", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317235EMAB123C456", "", "258", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317236EMAB123C456", "", "259", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317237EMAB123C456", "", "260", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317238EMAB123C456", "", "261", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112317239EMAB123C456", "", "262", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7230EMAB123C456", "", "263", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7231EMAB123C456", "", "264", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7232EMAB123C456", "", "265", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7233EMAB123C456", "", "266", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7234EMAB123C456", "", "267", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7235EMAB123C456", "", "268", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7236EMAB123C456", "", "269", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7237EMAB123C456", "", "270", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7238EMAB123C456", "", "271", new string[0])]
        [global::Xunit.InlineDataAttribute("8004950600098RP7849400245[GS]7239EMAB123C456", "", "272", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]1731123172401EA06672749541", "", "273", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]72401EA006672749541", "", "274", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]724110", "", "275", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]724110", "", "276", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]7242117.43.8092.7", "", "277", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7242117.43.8092.7", "", "278", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]725019630403", "", "279", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7251196304030100", "", "280", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]72521", "", "281", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7257Av.+Louise+326", "", "282", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7259SMITH01", "", "283", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]7253SMITH", "", "284", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]7254JOHN", "", "285", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]7255Jr", "", "286", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]7256JOHN+SMITH+JR", "", "287", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7253SMITH", "", "288", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7254JOHN", "", "289", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7255Jr", "", "290", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]7256JOHN+SMITH+JR", "", "291", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]72581/1[GS]7259SMITH01", "", "292", new string[0])]
        [global::Xunit.InlineDataAttribute("0109506000134376800110000010010010", "", "293", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112318005001250", "", "294", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]8005001250", "", "295", new string[0])]
        [global::Xunit.InlineDataAttribute("8020000B231297726310000[GS]8007GB29NWBK60161331926819[GS]4159506000134376", "", "296", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]173112318008251228115214", "", "297", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650200209506000134376173112313710[GS]8008251228115214", "", "298", new string[0])]
        [global::Xunit.InlineDataAttribute("00950600098427565020010950600013437610ABC123[GS]17311231800901/TEMP/MAX=008C/DUR=" +
            "120H/ALGO=TTI1", "", "299", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231800901/TEMP/MAX=008C/DUR=120H/ALGO=TTI1", "", "300", new string[0])]
        [global::Xunit.InlineDataAttribute("8010950600048AG56320100B#12[GS]80115883078132", "", "301", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437610ABC123[GS]17311231801215.0.4701.1001", "", "302", new string[0])]
        [global::Xunit.InlineDataAttribute("10ABC123[GS]8006095060001343760310[GS]801215.0.4701.1001", "", "303", new string[0])]
        [global::Xunit.InlineDataAttribute("010950600013437680141987654Ad4X4bL5ttr2310c2K", "", "304", new string[0])]
        [global::Xunit.InlineDataAttribute("8017950600098427565020[GS]80190030562094", "", "305", new string[0])]
        [global::Xunit.InlineDataAttribute("8018950600098427565020[GS]80190030562094", "", "306", new string[0])]
        [global::Xunit.InlineDataAttribute("41595060001343768020R470364122BJ5", "", "307", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650208026095060001343760310[GS]37144", "", "308", new string[0])]
        [global::Xunit.InlineDataAttribute("01095060001343762123560917519861[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_" +
            "vZmZZVgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "309", new string[0])]
        [global::Xunit.InlineDataAttribute("8006095060001343760310[GS]2123560917519861[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV8" +
            "9rrRoAYU1_vZmZZVgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "310", new string[0])]
        [global::Xunit.InlineDataAttribute("8010950600048AG56320100B#12[GS]80115883078132[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_Kpv" +
            "zV89rrRoAYU1_vZmZZVgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "311", new string[0])]
        [global::Xunit.InlineDataAttribute("80030506091751000434B1UL09036[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZm" +
            "ZZVgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "312", new string[0])]
        [global::Xunit.InlineDataAttribute("80045060917ASSET+0001[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZY" +
            "zoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "313", new string[0])]
        [global::Xunit.InlineDataAttribute("8017506091751000315180[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZ" +
            "Yzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "314", new string[0])]
        [global::Xunit.InlineDataAttribute("8018506091751000315180[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZ" +
            "Yzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "315", new string[0])]
        [global::Xunit.InlineDataAttribute("009506000984275650208030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZYzoimi" +
            "dtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "316", new string[0])]
        [global::Xunit.InlineDataAttribute("2531234567890128733AC720317439R36[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1" +
            "_vZmZZVgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "317", new string[0])]
        [global::Xunit.InlineDataAttribute("2551234567890128733720317439[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZ" +
            "ZVgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "318", new string[0])]
        [global::Xunit.InlineDataAttribute("2551234567890128733720317439[GS]81110946", "", "319", new string[0])]
        [global::Xunit.InlineDataAttribute("01012345678901288200http://example.com", "", "320", new string[0])]
        public async global::System.Threading.Tasks.Task ValidateDataRelationshipsBetweenMultipleDataElements(string input, string semantics, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("semantics", semantics);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate data relationships between multiple data elements", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
    await testRunner.AndAsync(string.Format("the semantics are {0}", semantics), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.WhenAsync("the input to submitted to the parser and data relationship tests are required", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
 await testRunner.ThenAsync("there should be no errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Detect missing mandatory data relationships")]
        [global::Xunit.TraitAttribute("FeatureTitle", "DataRelationships")]
        [global::Xunit.TraitAttribute("Description", "Detect missing mandatory data relationships")]
        [global::Xunit.InlineDataAttribute("01", "010950600013437610ABC123[GS]17311231", "01.VariableMeasure", "321", new string[0])]
        [global::Xunit.InlineDataAttribute("01", "019950600013437910ABC123[GS]17311231", "01.VariableMeasure", "322", new string[0])]
        [global::Xunit.InlineDataAttribute("02", "00950600098427565020029950600013437910ABC123[GS]173112313710", "01.VariableMeasure", "323", new string[0])]
        [global::Xunit.InlineDataAttribute("01", "019950600013437910ABC123[GS]17311231", "01.Custom", "324", new string[0])]
        [global::Xunit.InlineDataAttribute("02", "020950600013437610ABC123", "", "325", new string[0])]
        [global::Xunit.InlineDataAttribute("02", "009506000984275650200200235060917511", "", "326", new string[0])]
        [global::Xunit.InlineDataAttribute("02", "02002350609175113710", "", "327", new string[0])]
        [global::Xunit.InlineDataAttribute("10", "10ABC123[GS]17311231", "", "328", new string[0])]
        [global::Xunit.InlineDataAttribute("11", "10ABC123[GS]11251221", "", "329", new string[0])]
        [global::Xunit.InlineDataAttribute("13", "ABC123[GS]13251221", "", "330", new string[0])]
        [global::Xunit.InlineDataAttribute("15", "ABC123[GS]15260103", "", "331", new string[0])]
        [global::Xunit.InlineDataAttribute("16", "10ABC123[GS]16261102", "", "332", new string[0])]
        [global::Xunit.InlineDataAttribute("17", "10ABC123[GS]17260103", "", "333", new string[0])]
        [global::Xunit.InlineDataAttribute("12", "12251231", "", "334", new string[0])]
        [global::Xunit.InlineDataAttribute("12", "1225123180201438940A32", "", "335", new string[0])]
        [global::Xunit.InlineDataAttribute("12", "122512314159506000134376", "", "336", new string[0])]
        [global::Xunit.InlineDataAttribute("17", "10ABC123[GS]172601038006095060001343760310", "17.Coupon", "337", new string[0])]
        [global::Xunit.InlineDataAttribute("20", "200317311231", "", "338", new string[0])]
        [global::Xunit.InlineDataAttribute("21", "2149950304162", "", "339", new string[0])]
        [global::Xunit.InlineDataAttribute("22", "2249950A304162", "", "340", new string[0])]
        [global::Xunit.InlineDataAttribute("235", "2351ABC36610835978537", "", "341", new string[0])]
        [global::Xunit.InlineDataAttribute("240", "24049950A304162", "", "342", new string[0])]
        [global::Xunit.InlineDataAttribute("241", "24149950A304162", "", "343", new string[0])]
        [global::Xunit.InlineDataAttribute("242", "24223", "", "344", new string[0])]
        [global::Xunit.InlineDataAttribute("242", "010950600013437624223[GS]17311231", "", "345", new string[0])]
        [global::Xunit.InlineDataAttribute("242", "00950600098427565020020950600013437624223[GS]173112313710", "", "346", new string[0])]
        [global::Xunit.InlineDataAttribute("242", "24223[GS]8006095060001343760310", "", "347", new string[0])]
        [global::Xunit.InlineDataAttribute("242", "0095060009842756502024223[GS]8026095060001343760310[GS]3710", "", "348", new string[0])]
        [global::Xunit.InlineDataAttribute("243", "2431ABC36610835978537", "", "349", new string[0])]
        [global::Xunit.InlineDataAttribute("250", "25049950304162", "", "350", new string[0])]
        [global::Xunit.InlineDataAttribute("250", "010950600013437625049950304162", "", "351", new string[0])]
        [global::Xunit.InlineDataAttribute("250", "8006095060001343760310[GS]25049950304162", "", "352", new string[0])]
        [global::Xunit.InlineDataAttribute("250", "25049950304162[GS]218801005795367", "", "353", new string[0])]
        [global::Xunit.InlineDataAttribute("251", "25149950304162", "", "354", new string[0])]
        [global::Xunit.InlineDataAttribute("254", "254JJ429", "", "355", new string[0])]
        [global::Xunit.InlineDataAttribute("30", "30100", "", "356", new string[0])]
        [global::Xunit.InlineDataAttribute("3100", "3100000001", "", "357", new string[0])]
        [global::Xunit.InlineDataAttribute("3200", "3200000001", "", "358", new string[0])]
        [global::Xunit.InlineDataAttribute("3500", "3500000001", "", "359", new string[0])]
        [global::Xunit.InlineDataAttribute("3600", "3600000001", "", "360", new string[0])]
        [global::Xunit.InlineDataAttribute("3330", "3330000001", "", "361", new string[0])]
        [global::Xunit.InlineDataAttribute("3430", "3430000001", "", "362", new string[0])]
        [global::Xunit.InlineDataAttribute("3530", "3530000001", "", "363", new string[0])]
        [global::Xunit.InlineDataAttribute("3630", "3630000001", "", "364", new string[0])]
        [global::Xunit.InlineDataAttribute("3372", "3372001458", "", "365", new string[0])]
        [global::Xunit.InlineDataAttribute("37", "37637144[GS]10ABC123", "", "366", new string[0])]
        [global::Xunit.InlineDataAttribute("3902", "39023902001458", "", "367", new string[0])]
        [global::Xunit.InlineDataAttribute("3902", "8020R470364122BJ5[GS]3902001458[GS]", "", "368", new string[0])]
        [global::Xunit.InlineDataAttribute("3902", "3902001458[GS]4159506000134376", "", "369", new string[0])]
        [global::Xunit.InlineDataAttribute("3902", "39023902001458", "3902.CouponValue", "370", new string[0])]
        [global::Xunit.InlineDataAttribute("3912", "39129783902001458", "", "371", new string[0])]
        [global::Xunit.InlineDataAttribute("3912", "8020R470364122BJ5[GS]3912978001458[GS]", "", "372", new string[0])]
        [global::Xunit.InlineDataAttribute("3912", "3912978001458[GS]4159506000134376", "", "373", new string[0])]
        [global::Xunit.InlineDataAttribute("3922", "010950600013437610ABC123[GS]3922001458", "", "374", new string[0])]
        [global::Xunit.InlineDataAttribute("3932", "010950600013437610ABC123[GS]3932978001458", "", "375", new string[0])]
        [global::Xunit.InlineDataAttribute("3940", "39400010", "", "376", new string[0])]
        [global::Xunit.InlineDataAttribute("3952", "010950600013437610ABC123[GS]3952001458", "", "377", new string[0])]
        [global::Xunit.InlineDataAttribute("403", "403GBR4720045198", "", "378", new string[0])]
        [global::Xunit.InlineDataAttribute("415", "4159506000134376", "", "379", new string[0])]
        [global::Xunit.InlineDataAttribute("422", "422826", "", "380", new string[0])]
        [global::Xunit.InlineDataAttribute("423", "423826250276", "", "381", new string[0])]
        [global::Xunit.InlineDataAttribute("424", "424826", "", "382", new string[0])]
        [global::Xunit.InlineDataAttribute("425", "425826250276", "", "383", new string[0])]
        [global::Xunit.InlineDataAttribute("426", "426826", "", "384", new string[0])]
        [global::Xunit.InlineDataAttribute("427", "422826[GS]427826", "", "385", new string[0])]
        [global::Xunit.InlineDataAttribute("427", "010950600013437610ABC123[GS]17311231427826", "", "386", new string[0])]
        [global::Xunit.InlineDataAttribute("427", "009506000984275650200209506000134376173112313710[GS]427826", "", "387", new string[0])]
        [global::Xunit.InlineDataAttribute("4300", "4300ACME+LIMITED", "", "388", new string[0])]
        [global::Xunit.InlineDataAttribute("4301", "4301JOHN+SMITH", "", "389", new string[0])]
        [global::Xunit.InlineDataAttribute("4302", "4302UNIT+5", "", "390", new string[0])]
        [global::Xunit.InlineDataAttribute("4304", "4304UPPER+NETHERBY", "", "391", new string[0])]
        [global::Xunit.InlineDataAttribute("4305", "4305WESTGATE", "", "392", new string[0])]
        [global::Xunit.InlineDataAttribute("4306", "4306BILLINGSHIRE", "", "393", new string[0])]
        [global::Xunit.InlineDataAttribute("4307", "4307GB", "", "394", new string[0])]
        [global::Xunit.InlineDataAttribute("4308", "430801379250388", "", "395", new string[0])]
        [global::Xunit.InlineDataAttribute("4303", "4303ELM+STREET+BUSINESS+PARK", "", "396", new string[0])]
        [global::Xunit.InlineDataAttribute("4303", "4302UNIT+5[GS]4303ELM+STREET+BUSINESS+PARK", "", "397", new string[0])]
        [global::Xunit.InlineDataAttribute("4303", "009506000984275650204303ELM+STREET+BUSINESS+PARK", "", "398", new string[0])]
        [global::Xunit.InlineDataAttribute("4309", "430902790858483015297971", "", "399", new string[0])]
        [global::Xunit.InlineDataAttribute("4310", "4310ACME+LIMITED", "", "400", new string[0])]
        [global::Xunit.InlineDataAttribute("4311", "4311JOHN+SMITH", "", "401", new string[0])]
        [global::Xunit.InlineDataAttribute("4312", "4312UNIT+5", "", "402", new string[0])]
        [global::Xunit.InlineDataAttribute("4314", "4314UPPER+NETHERBY", "", "403", new string[0])]
        [global::Xunit.InlineDataAttribute("4315", "4315WESTGATE", "", "404", new string[0])]
        [global::Xunit.InlineDataAttribute("4316", "4316BILLINGSHIRE", "", "405", new string[0])]
        [global::Xunit.InlineDataAttribute("4317", "4317GB", "", "406", new string[0])]
        [global::Xunit.InlineDataAttribute("4318", "431801379250388", "", "407", new string[0])]
        [global::Xunit.InlineDataAttribute("4319", "431902790858483015297971", "", "408", new string[0])]
        [global::Xunit.InlineDataAttribute("4313", "4313ELM+STREET+BUSINESS+PARK", "", "409", new string[0])]
        [global::Xunit.InlineDataAttribute("4313", "4312UNIT+5[GS]4313ELM+STREET+BUSINESS+PARK", "", "410", new string[0])]
        [global::Xunit.InlineDataAttribute("4313", "009506000984275650204313ELM+STREET+BUSINESS+PARK", "", "411", new string[0])]
        [global::Xunit.InlineDataAttribute("4320", "4320HANDLE+WITH+CARE", "", "412", new string[0])]
        [global::Xunit.InlineDataAttribute("4321", "43211", "", "413", new string[0])]
        [global::Xunit.InlineDataAttribute("4322", "43221", "", "414", new string[0])]
        [global::Xunit.InlineDataAttribute("4323", "43231", "", "415", new string[0])]
        [global::Xunit.InlineDataAttribute("4324", "43242512271300", "", "416", new string[0])]
        [global::Xunit.InlineDataAttribute("4325", "43252512271300", "", "417", new string[0])]
        [global::Xunit.InlineDataAttribute("4326", "4326260131", "", "418", new string[0])]
        [global::Xunit.InlineDataAttribute("4330", "4330023020", "", "419", new string[0])]
        [global::Xunit.InlineDataAttribute("4331", "4331000090", "", "420", new string[0])]
        [global::Xunit.InlineDataAttribute("4332", "4332023020", "", "421", new string[0])]
        [global::Xunit.InlineDataAttribute("4333", "4333000090", "", "422", new string[0])]
        [global::Xunit.InlineDataAttribute("7001", "70011005000739421", "", "423", new string[0])]
        [global::Xunit.InlineDataAttribute("7002", "700210164300153201040050", "", "424", new string[0])]
        [global::Xunit.InlineDataAttribute("7003", "70032603311200", "", "425", new string[0])]
        [global::Xunit.InlineDataAttribute("7004", "70043107", "", "426", new string[0])]
        [global::Xunit.InlineDataAttribute("7004", "010950600013437670043107", "", "427", new string[0])]
        [global::Xunit.InlineDataAttribute("7004", "10ABC123[GS]1731123170043107", "", "428", new string[0])]
        [global::Xunit.InlineDataAttribute("7005", "700527.8.e.2", "", "429", new string[0])]
        [global::Xunit.InlineDataAttribute("7006", "7006251227", "", "430", new string[0])]
        [global::Xunit.InlineDataAttribute("7007", "7007250803250817", "", "431", new string[0])]
        [global::Xunit.InlineDataAttribute("7008", "7008BOH", "", "432", new string[0])]
        [global::Xunit.InlineDataAttribute("7009", "700909.31", "", "433", new string[0])]
        [global::Xunit.InlineDataAttribute("7010", "701001", "", "434", new string[0])]
        [global::Xunit.InlineDataAttribute("7011", "70112603151200", "", "435", new string[0])]
        [global::Xunit.InlineDataAttribute("7030", "7030826AB123C456", "", "436", new string[0])]
        [global::Xunit.InlineDataAttribute("7031", "7031826AB123C456", "", "437", new string[0])]
        [global::Xunit.InlineDataAttribute("7032", "7032826AB123C456", "", "438", new string[0])]
        [global::Xunit.InlineDataAttribute("7033", "7033826AB123C456", "", "439", new string[0])]
        [global::Xunit.InlineDataAttribute("7034", "7034826AB123C456", "", "440", new string[0])]
        [global::Xunit.InlineDataAttribute("7035", "7035826AB123C456", "", "441", new string[0])]
        [global::Xunit.InlineDataAttribute("7036", "7036826AB123C456", "", "442", new string[0])]
        [global::Xunit.InlineDataAttribute("7037", "7037826AB123C456", "", "443", new string[0])]
        [global::Xunit.InlineDataAttribute("7038", "7038826AB123C456", "", "444", new string[0])]
        [global::Xunit.InlineDataAttribute("7039", "7039826AB123C456", "", "445", new string[0])]
        [global::Xunit.InlineDataAttribute("710", "71027580899", "", "446", new string[0])]
        [global::Xunit.InlineDataAttribute("711", "7113400123456789", "", "447", new string[0])]
        [global::Xunit.InlineDataAttribute("712", "712244137.8", "", "448", new string[0])]
        [global::Xunit.InlineDataAttribute("713", "7131234567890123", "", "449", new string[0])]
        [global::Xunit.InlineDataAttribute("714", "7145551643", "", "450", new string[0])]
        [global::Xunit.InlineDataAttribute("715", "71500781150610", "", "451", new string[0])]
        [global::Xunit.InlineDataAttribute("716", "716365820310", "", "452", new string[0])]
        [global::Xunit.InlineDataAttribute("717", "717M-ES-20-00283", "", "453", new string[0])]
        [global::Xunit.InlineDataAttribute("7020", "7020ABC123", "", "454", new string[0])]
        [global::Xunit.InlineDataAttribute("7020", "01095060001343767020ABC123", "", "455", new string[0])]
        [global::Xunit.InlineDataAttribute("7020", "8006095060001343760310[GS]7020ABC123", "", "456", new string[0])]
        [global::Xunit.InlineDataAttribute("7020", "7020ABC123[GS]4169506000134376", "", "457", new string[0])]
        [global::Xunit.InlineDataAttribute("7021", "7021APPROVED2512", "", "458", new string[0])]
        [global::Xunit.InlineDataAttribute("7022", "70224.178", "", "459", new string[0])]
        [global::Xunit.InlineDataAttribute("7022", "010950600013437670224.178", "", "460", new string[0])]
        [global::Xunit.InlineDataAttribute("7022", "8006095060001343760310[GS]70224.178", "", "461", new string[0])]
        [global::Xunit.InlineDataAttribute("7022", "70224.178[GS]7021APPROVED2512", "", "462", new string[0])]
        [global::Xunit.InlineDataAttribute("7041", "70414A", "", "463", new string[0])]
        [global::Xunit.InlineDataAttribute("7230", "7230AB123C456", "", "464", new string[0])]
        [global::Xunit.InlineDataAttribute("7231", "7231AB123C456", "", "465", new string[0])]
        [global::Xunit.InlineDataAttribute("7232", "7232AB123C456", "", "466", new string[0])]
        [global::Xunit.InlineDataAttribute("7233", "7233AB123C456", "", "467", new string[0])]
        [global::Xunit.InlineDataAttribute("7234", "7234AB123C456", "", "468", new string[0])]
        [global::Xunit.InlineDataAttribute("7235", "7235AB123C456", "", "469", new string[0])]
        [global::Xunit.InlineDataAttribute("7236", "7236AB123C456", "", "470", new string[0])]
        [global::Xunit.InlineDataAttribute("7237", "7237AB123C456", "", "471", new string[0])]
        [global::Xunit.InlineDataAttribute("7238", "7238AB123C456", "", "472", new string[0])]
        [global::Xunit.InlineDataAttribute("7239", "7239AB123C456", "", "473", new string[0])]
        [global::Xunit.InlineDataAttribute("7240", "72401EA06672749541", "", "474", new string[0])]
        [global::Xunit.InlineDataAttribute("7241", "724110", "", "475", new string[0])]
        [global::Xunit.InlineDataAttribute("7242", "7242117.43.8092.7", "", "476", new string[0])]
        [global::Xunit.InlineDataAttribute("7250", "725019630403", "", "477", new string[0])]
        [global::Xunit.InlineDataAttribute("7251", "7251196304030100", "", "478", new string[0])]
        [global::Xunit.InlineDataAttribute("7252", "72521", "", "479", new string[0])]
        [global::Xunit.InlineDataAttribute("7257", "7257Av.+Louise+326", "", "480", new string[0])]
        [global::Xunit.InlineDataAttribute("7259", "7259SMITH01", "", "481", new string[0])]
        [global::Xunit.InlineDataAttribute("7253", "7253SMITH", "", "482", new string[0])]
        [global::Xunit.InlineDataAttribute("7254", "7254JOHN", "", "483", new string[0])]
        [global::Xunit.InlineDataAttribute("7255", "7255Jr", "", "484", new string[0])]
        [global::Xunit.InlineDataAttribute("7256", "7256JOHN+SMITH+JR", "", "485", new string[0])]
        [global::Xunit.InlineDataAttribute("7258", "72581/1", "", "486", new string[0])]
        [global::Xunit.InlineDataAttribute("7258", "72581/17259SMITH01", "", "487", new string[0])]
        [global::Xunit.InlineDataAttribute("7258", "8018950600098427565020[GS]72581/1", "", "488", new string[0])]
        [global::Xunit.InlineDataAttribute("8001", "800110000010010010", "", "489", new string[0])]
        [global::Xunit.InlineDataAttribute("8005", "8005001250", "", "490", new string[0])]
        [global::Xunit.InlineDataAttribute("8007", "8007GB29NWBK60161331926819", "", "491", new string[0])]
        [global::Xunit.InlineDataAttribute("8007", "8007GB29NWBK60161331926819[GS]41509506000134376", "", "492", new string[0])]
        [global::Xunit.InlineDataAttribute("8007", "8020000B231297726310000[GS]8007GB29NWBK60161331926819", "", "493", new string[0])]
        [global::Xunit.InlineDataAttribute("8008", "8008251228115214", "", "494", new string[0])]
        [global::Xunit.InlineDataAttribute("8009", "800901/TEMP/MAX=008C/DUR=120H/ALGO=TTI1", "", "495", new string[0])]
        [global::Xunit.InlineDataAttribute("8011", "80115883078132", "", "496", new string[0])]
        [global::Xunit.InlineDataAttribute("8012", "801215.0.4701.1001", "", "497", new string[0])]
        [global::Xunit.InlineDataAttribute("8014", "80141987654Ad4X4bL5ttr2310c2K", "", "498", new string[0])]
        [global::Xunit.InlineDataAttribute("8019", "80190030562094", "", "499", new string[0])]
        [global::Xunit.InlineDataAttribute("8020", "8020R470364122BJ5", "", "500", new string[0])]
        [global::Xunit.InlineDataAttribute("8026", "8026095060001343760310", "", "501", new string[0])]
        [global::Xunit.InlineDataAttribute("8026", "009506000984275650208026095060001343760310", "", "502", new string[0])]
        [global::Xunit.InlineDataAttribute("8026", "8026095060001343760310[GS]37144", "", "503", new string[0])]
        [global::Xunit.InlineDataAttribute("8030", "8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZYzoimidtx15-GKrMpIqMoGBilY" +
            "ABllltNkVZpppppsA", "", "504", new string[0])]
        [global::Xunit.InlineDataAttribute("8030", "01095060001343768030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZYzoimidtx1" +
            "5-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "505", new string[0])]
        [global::Xunit.InlineDataAttribute("8030", "2123560917519861[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZYzoimi" +
            "dtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "506", new string[0])]
        [global::Xunit.InlineDataAttribute("8030", "8006095060001343760310[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZVgNpZ" +
            "Yzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "507", new string[0])]
        [global::Xunit.InlineDataAttribute("8030", "8010950600048AG56320100B#12[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZ" +
            "VgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "508", new string[0])]
        [global::Xunit.InlineDataAttribute("8030", "8011950600048AG56320100B#12[GS]8030SgmLUBtmxgI-jeh6y_E-wv7B_KpvzV89rrRoAYU1_vZmZZ" +
            "VgNpZYzoimidtx15-GKrMpIqMoGBilYABllltNkVZpppppsA", "", "509", new string[0])]
        [global::Xunit.InlineDataAttribute("8111", "81110946", "", "510", new string[0])]
        [global::Xunit.InlineDataAttribute("8200", "8200http://example.com", "", "511", new string[0])]
        public async global::System.Threading.Tasks.Task DetectMissingMandatoryDataRelationships(string ai, string input, string semantics, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("semantics", semantics);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Detect missing mandatory data relationships", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 538
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 539
 await testRunner.GivenAsync(string.Format("the input is {0}", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 540
    await testRunner.AndAsync(string.Format("the semantics are {0}", semantics), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 541
 await testRunner.WhenAsync("the input to submitted to the parser and data relationship tests are required", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 542
    await testRunner.ThenAsync(string.Format("we should detect AI {0}", ai), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 543
    await testRunner.AndAsync("the errors should include a fatal 2203 error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DataRelationshipsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DataRelationshipsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
