// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Solidsoft.Reply.Parsers.Gs1Ai.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PatternBoundsFeature : object, Xunit.IClassFixture<PatternBoundsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PatternBounds.feature"
#line hidden
        
        public PatternBoundsFeature(PatternBoundsFeature.FixtureData fixtureData, Solidsoft_Reply_Parsers_Gs1Ai_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "PatternBounds", "Tests for valid boundary conditions and character sets.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="MaxEightDigitValue")]
        [Xunit.TraitAttribute("FeatureTitle", "PatternBounds")]
        [Xunit.TraitAttribute("Description", "MaxEightDigitValue")]
        [Xunit.InlineDataAttribute("@N2+N..8", "37", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N..8", "37", "", "00000000", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N..8", "37", "", "99999999", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N14", "01", "", "00000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N14", "01", "", "99999999999997", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N18", "00", "", "000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N18", "00", "", "999999999999999995", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N2", "20", "", "00", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N2", "20", "", "99", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N6", "11", "", "000100", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N6", "11", "", "991231", new string[0])]
        [Xunit.InlineDataAttribute("@N2+N6", "11", "", "991200", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "00000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "99999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "ABCDEFGHIJKLMNOPQRST", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "UVWXYZabcdefghijklmn", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "opqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "90!\"%&\'()*+,-./:;<=>", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..20", "10", "", "?_", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..30", "90", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..30", "90", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..30", "90", "", "999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..30", "90", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcd", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..30", "90", "", "efghijklmnopqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..30", "90", "", "90!\"%&\'()*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..90", "91", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..90", "91", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..90", "91", "", "999999999999999999999999999999999999999999999999999999999999999999999999999999999" +
            "999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N2+X..90", "91", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\"%&\'()*+,-./:;<=>?" +
            "_", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N..6", "242", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N..6", "242", "", "000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N..6", "242", "", "1", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N..6", "242", "", "999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+N..12]", "255", "", "0000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+N..12]", "255", "", "9999999999994", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+N..12]", "255", "", "00000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+N..12]", "255", "", "99999999999940", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+N..12]", "255", "", "0000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+N..12]", "255", "", "0000000000000999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "0000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "9999999999994", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "00000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "99999999999940", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "000000000000099999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "0000000000000ABCDEFGHIJKLMNOPQ", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "0000000000000RSTUVWXYZabcdefgh", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "0000000000000ijklmnopqrstuvwxy", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "0000000000000z1234567890!\"%&\'(", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13[+X..17]", "253", "", "0000000000000)*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13", "410", "", "0000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N13", "410", "", "9999999999994", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N17", "402", "", "00000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N17", "402", "", "99999999999999992", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+N..12", "423", "", "826", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+N..12", "423", "", "826840", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+N..12", "423", "", "826840740", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+N..12", "423", "", "826840740620", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+N..12", "423", "", "826840740620417", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "8261", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826A", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826ABCDEFGHI", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826JKLMNOPQR", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826STUVWXYZa", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826bcdefghij", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826klmnopqrs", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826tuvwxyz12", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "82634567890!", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826\"%&\'()*+,", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826-./:;<=>?", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3+X..9", "421", "", "826_", new string[0])]
        [Xunit.InlineDataAttribute("@N3+N3", "422", "", "826", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "00000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "99999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "ABCDEFGHIJKLMNOPQRST", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "UVWXYZabcdefghijklmn", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "opqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "90!\"%&\'()*+,-./:;<=>", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..20", "243", "", "?_", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "0000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "9999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZab", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "cdefghijklmnopqrstuvwxyz1234", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..28", "235", "", "567890!\"%&\'()*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcd", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "efghijklmnopqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..30", "240", "", "90!\"%&\'()*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "000", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "999", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "ABC", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "DEF", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "GHI", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "JKL", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "MNO", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "PQR", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "STU", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "VWX", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "YZa", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "bcd", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "efg", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "hij", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "klm", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "nop", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "qrs", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "tuv", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "wxy", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "z12", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "345", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "678", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "90!", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "\"%&", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "\'()", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "*+,", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "-./", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", ":;<", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "=>?", new string[0])]
        [Xunit.InlineDataAttribute("@N3+X..3", "427", "", "_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..10", "8019", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..10", "8019", "", "0000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..10", "8019", "", "9999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..12", "8011", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..12", "8011", "", "000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..12", "8011", "", "999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..15", "390", "2", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..15", "390", "2", "000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..15", "390", "2", "999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..4", "7004", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..4", "7004", "", "0000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N..4", "7004", "", "9999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "9999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0ABC", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0DEF", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0GHI", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0JKL", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0MNO", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0PQR", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0STU", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0VWX", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0YZa", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0bcd", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0efg", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0hij", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0klm", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0nop", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0qrs", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0tuv", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0wxy", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0z12", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0345", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "090!", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0\"%&", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0\'()", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0*+,", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0-./", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0:;<", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0=>?", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1+X3", "7040", "", "0___", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N10", "4324", "", "0001010000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N10", "4324", "", "9912319999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N13", "7001", "", "0000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N13", "7001", "", "9999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14+N2+N2", "8006", "", "000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14+N2+N2", "8006", "", "999999999999979999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "00000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "099999999999940", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "099999999999940000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "099999999999949999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994ABCDEFGHIJKLMNOP", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994QRSTUVWXYZabcdef", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994ghijklmnopqrstuv", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994wxyz1234567890!\"", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994%&\'()*+,-./:;<=>", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14[+X..16]", "8003", "", "09999999999994?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14", "8001", "", "00000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N14", "8001", "", "99999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N18", "8017", "", "000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N18", "8017", "", "999999999999999995", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1", "4321", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N1", "4321", "", "1", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N20", "4309", "", "00000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N20", "4309", "", "99999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+N..15", "391", "2", "0000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+N..15", "391", "2", "9990", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+N..15", "391", "2", "000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+N..15", "391", "2", "999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "9990", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "999A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "999000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "999ABCDEFGHIJKLMNOPQRSTUVWXYZa", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "999bcdefghijklmnopqrstuvwxyz12", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "99934567890!\"%&\'()*+,-./:;<=>?", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N3+X..27", "703", "0", "999_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N4", "394", "2", "0000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N4", "394", "2", "9999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N4", "8111", "", "0000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N4", "8111", "", "9999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6[+N4]", "7011", "", "000101", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6[+N4]", "7011", "", "991231", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6[+N4]", "7011", "", "9912310000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6[+N6]", "7007", "", "9912312359", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6", "310", "2", "000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6", "310", "2", "999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6", "8005", "", "000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6", "8005", "", "999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6", "4326", "", "000101", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N6", "4326", "", "991231", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N8[+N..4]", "8008", "", "00010100", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N8[+N..4]", "8008", "", "99123123", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N8[+N..4]", "8008", "", "991231230000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+N8[+N..4]", "8008", "", "991231235959", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "0000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "9999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "ABCDEFGHIJ", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "KLMNOPQRST", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "UVWXYZabcd", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "efghijklmn", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "opqrstuvwx", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "yz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "90!\"%&\'()*", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "+,-./:;<=>", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..10", "7009", "", "?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "ABCDEFGHIJKL", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "MNOPQRSTUVWX", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "YZabcdefghij", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "klmnopqrstuv", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "wxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "90!\"%&\'()*+,", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..12", "7005", "", "-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "00000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "99999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "ABCDEFGHIJKLMNOPQRST", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "UVWXYZabcdefghijklmn", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "opqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "90!\"%&\'()*+,-./:;<=>", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..20", "4318", "", "?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "0000000000000000000000065", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "99999999999999999999999UL", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "99999999999999999999999UL", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "99999ABCDEFGHIJKLMNOPQRQM", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "99999STUVWXYZabcdefghijPB", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "99999klmnopqrstuvwxyz12JY", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "9999934567890!\"%&\'()*+,ZQ", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8013", "", "99999-./:;<=>?_ABCDEFGH5G", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "0000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "9999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "ABCDEFGHIJKLMNOPQRSTUVWXY", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "Zabcdefghijklmnopqrstuvwx", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", "yz1234567890!\"%&\'()*+,-./", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..25", "8020", "", ":;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..2", "7010", "", "01", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..2", "7010", "", "04", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "9", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcd", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "efghijklmnopqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..30", "4308", "", "90!\"%&\'()*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "9", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "0000000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "9999999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "ijklmnopqrstuvwxyz1234567890!\"%&\'(", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..34", "8007", "", ")*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "9", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "00000000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "99999999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghi", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "jklmnopqrstuvwxyz1234567890!\"%&\'()*", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..35", "4300", "", "+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "A", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "ABC", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "DEF", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "GHI", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "JKL", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "MNO", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "PQR", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "STU", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "VWX", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "YZa", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "bcd", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "efg", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "hij", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "klm", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "nop", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "qrs", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "tuv", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "wxy", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "z12", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "345", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "90!", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "\"%&", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "\'()", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "*+,", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "-./", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", ":;<", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "=>?", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..3", "7008", "", "_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..50", "8009", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..50", "8009", "", "9", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..50", "8009", "", "00000000000000000000000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..50", "8009", "", "99999999999999999999999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..50", "8009", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..50", "8009", "", "yz1234567890!\"%&\'()*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..70", "4302", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..70", "4302", "", "9", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..70", "4302", "", "0000000000000000000000000000000000000000000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..70", "4302", "", "9999999999999999999999999999999999999999999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..70", "4302", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\"%&\'()*", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X..70", "4302", "", "+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcd", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "efghijklmnopqrstuvwxyz12345678", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2+X..28", "723", "0", "90!\"%&\'()*+,-./:;<=>?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "00", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "99", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "AB", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "CD", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "EF", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "GH", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "IJ", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "KL", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "MN", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "OP", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "QR", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "ST", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "UV", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "WX", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "YZ", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "ab", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "cd", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "ef", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "gh", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "ij", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "kl", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "mn", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "op", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "qr", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "st", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "uv", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "wx", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "yz", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "12", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "34", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "56", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "78", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "90", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "%&", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "!\"", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "\'(", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", ")*", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "+,", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "-.", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "/:", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", ";<", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "=>", new string[0])]
        [Xunit.InlineDataAttribute("@N4+X2", "4307", "", "?_", new string[0])]
        [Xunit.InlineDataAttribute("@N4+Y..30", "8010", "", "0", new string[0])]
        [Xunit.InlineDataAttribute("@N4+Y..30", "8010", "", "9", new string[0])]
        [Xunit.InlineDataAttribute("@N4+Y..30", "8010", "", "000000000000000000000000000000", new string[0])]
        [Xunit.InlineDataAttribute("@N4+Y..30", "8010", "", "999999999999999999999999999999", new string[0])]
        [Xunit.InlineDataAttribute("@N4+Y..30", "8010", "", "#-/0123456789ABCDEFGHIJKLMNOPQ", new string[0])]
        [Xunit.InlineDataAttribute("@N4+Y..30", "8010", "", "RSTUVWXYZ", new string[0])]
        public void MaxEightDigitValue(string pattern, string ai, string invexporseq, string countvalue, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("pattern", pattern);
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("invexporseq", invexporseq);
            argumentsOfScenario.Add("countvalue", countvalue);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MaxEightDigitValue", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given(string.Format("the input is {0}{1}{2}", ai, invexporseq, countvalue), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.When("the input to submitted to the parser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then(string.Format("the entity should be {0}", ai), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
     testRunner.And("there should be no errors", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PatternBoundsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PatternBoundsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
