// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Solidsoft.Reply.Parsers.Gs1Ai.Tests.Net6.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IBANValuesFeature : object, global::Xunit.IClassFixture<IBANValuesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "IBANValues", "Tests for valid boundary conditions and character sets.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Iban.feature"
#line hidden
        
        public IBANValuesFeature(IBANValuesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Iban.feature.ndjson", 73);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CountryIbanValues")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IBANValues")]
        [global::Xunit.TraitAttribute("Description", "CountryIbanValues")]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "AL47212110090000000235698741", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "AD1200012030200359100100", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "AT611904300234573201", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "BY13NBRB3600900000002Z00AB00", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "BE68539007547034", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "BA391290079401028494", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "BG80BNBG96611020345678", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "HR1210010051863000160", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "CY17002001280000001200527600", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "CZ6508000000192000145399", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "DK5000400440116243", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "EE382200221020145685", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "FO2000400440116243", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "FI2112345600000785", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "FR1420041010050500013M02606", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "DE89370400440532013000", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "GI75NWBK000000007099453", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "GR1601101250000000012300695", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "GL2000400440116243", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "HU42117730161111101800000000", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "IS140159260076545510730339", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "IE29AIBK93115212345678", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "IT60X0542811101000000123456", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "XK051212012345678906", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "LV80BANK0000435195001", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "LI21088100002324013AA", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "LT121000011101001000", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "LU280019400644750000", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "MK07250120000058984", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "MT84MALT011000012345MTLCAST001S", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "MD24AG000225100013104168", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "MC5811222000010123456789030", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "ME25505000012345678951", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "NL91ABNA0417164300", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "NO9386011117947", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "PL61109010140000071219812874", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "PT50000101231234567890192", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "RO49AAAA1B31007593840000", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "RS35260005601001611379", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "SK3112000000198742637541", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "SI56191000000123438", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "ES9121000418450200051332", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "SE4550000000058398257466", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "CH9300762011623852957", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "GB29NWBK60161331926819", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "AZ21NABZ00000000137010001944", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "BH67BMAG00001299123456", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "BR1800000000141455123924100C2", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "VG96VPVG0000012345678901", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "CR05015202001026284066", "49", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "DO28BAGR00000001212453611324", "50", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "SV62CENR00000000000000700025", "51", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "GE29NB0000000101904917", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "GT82TRAJ01020000001210029690", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "IQ98NBIQ850123456789012", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "IL620108000000099999999", "55", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "JO94CBJO0010000000000131000302", "56", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "KZ86125KZT5004100100", "57", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "KW81CBKU0000000000001234560101", "58", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "LB62099900000001001901229114", "59", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "MR1300020001010000123456753", "60", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "MU17BOMM0101101030300200000MUR", "61", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "PK36SCBL0000001123456702", "62", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "PS92PALS000000000400123456702", "63", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "QA73BBME000000000004056677001", "64", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "LC55HEMM000100010012001200023015", "65", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "ST68000100010051845310112", "66", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "SA0380000000608010167519", "67", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "TL380080012345678910157", "68", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "TN5910006035183598478831", "69", new string[0])]
        [global::Xunit.InlineDataAttribute("@N4+X..34", "8007", "", "TR330006100519786457841326", "70", new string[0])]
        public async global::System.Threading.Tasks.Task CountryIbanValues(string pattern, string ai, string invexporseq, string countvalue, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("pattern", pattern);
            argumentsOfScenario.Add("ai", ai);
            argumentsOfScenario.Add("invexporseq", invexporseq);
            argumentsOfScenario.Add("countvalue", countvalue);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CountryIbanValues", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync(string.Format("the input is {0}{1}{2}", ai, invexporseq, countvalue), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.WhenAsync("the input to submitted to the parser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.ThenAsync(string.Format("the entity should be {0}", ai), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
     await testRunner.AndAsync("there should be no errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IBANValuesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IBANValuesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
